#include "mfd_cli.h"
/* This file is generated by cli */

static result_t cli_config_uint8_name_value (cli_t *parser)
  {
  result_t result;
  const char * config_uint8_name_ = 0;
  uint16_t config_uint8_name_value_;

  if(failed(result = cli_get_string(&parser->tokens[1], &config_uint8_name_)))
    return result;

  if(failed(result = cli_get_uint16(&parser->tokens[2], &config_uint8_name_value_)))
    return result;

  result = config_uint8_name_value_action(parser, config_uint8_name_, config_uint8_name_value_);


  return result;
  }


static result_t cli_config_int8_name_value (cli_t *parser)
  {
  result_t result;
  const char * config_int8_name_ = 0;
  int16_t config_int8_name_value_;

  if(failed(result = cli_get_string(&parser->tokens[1], &config_int8_name_)))
    return result;

  if(failed(result = cli_get_int16(&parser->tokens[2], &config_int8_name_value_)))
    return result;

  result = config_int8_name_value_action(parser, config_int8_name_, config_int8_name_value_);


  return result;
  }


static result_t cli_config_uint16_name_value (cli_t *parser)
  {
  result_t result;
  const char * config_uint16_name_ = 0;
  uint16_t config_uint16_name_value_;

  if(failed(result = cli_get_string(&parser->tokens[1], &config_uint16_name_)))
    return result;

  if(failed(result = cli_get_uint16(&parser->tokens[2], &config_uint16_name_value_)))
    return result;

  result = config_uint16_name_value_action(parser, config_uint16_name_, config_uint16_name_value_);


  return result;
  }


static result_t cli_config_int16_name_value (cli_t *parser)
  {
  result_t result;
  const char * config_int16_name_ = 0;
  int16_t config_int16_name_value_;

  if(failed(result = cli_get_string(&parser->tokens[1], &config_int16_name_)))
    return result;

  if(failed(result = cli_get_int16(&parser->tokens[2], &config_int16_name_value_)))
    return result;

  result = config_int16_name_value_action(parser, config_int16_name_, config_int16_name_value_);


  return result;
  }


static result_t cli_config_uint32_name_value (cli_t *parser)
  {
  result_t result;
  const char * config_uint32_name_ = 0;
  uint32_t config_uint32_name_value_;

  if(failed(result = cli_get_string(&parser->tokens[1], &config_uint32_name_)))
    return result;

  if(failed(result = cli_get_uint32(&parser->tokens[2], &config_uint32_name_value_)))
    return result;

  result = config_uint32_name_value_action(parser, config_uint32_name_, config_uint32_name_value_);


  return result;
  }


static result_t cli_config_int32_name_value (cli_t *parser)
  {
  result_t result;
  const char * config_int32_name_ = 0;
  int32_t config_int32_name_value_;

  if(failed(result = cli_get_string(&parser->tokens[1], &config_int32_name_)))
    return result;

  if(failed(result = cli_get_int32(&parser->tokens[2], &config_int32_name_value_)))
    return result;

  result = config_int32_name_value_action(parser, config_int32_name_, config_int32_name_value_);


  return result;
  }


static result_t cli_config_xyz_name_value (cli_t *parser)
  {
  result_t result;
  const char * config_xyz_name_ = 0;
  xyz_t config_xyz_name_value_;

  if(failed(result = cli_get_string(&parser->tokens[1], &config_xyz_name_)))
    return result;

  if(failed(result = cli_get_xyz(&parser->tokens[2], &config_xyz_name_value_)))
    return result;

  result = config_xyz_name_value_action(parser, config_xyz_name_, &config_xyz_name_value_);


  return result;
  }


static result_t cli_config_matrix_name_value (cli_t *parser)
  {
  result_t result;
  const char * config_matrix_name_ = 0;
  matrix_t config_matrix_name_value_;

  if(failed(result = cli_get_string(&parser->tokens[1], &config_matrix_name_)))
    return result;

  if(failed(result = cli_get_matrix(&parser->tokens[2], &config_matrix_name_value_)))
    return result;

  result = config_matrix_name_value_action(parser, config_matrix_name_, &config_matrix_name_value_);


  return result;
  }


static result_t cli_config_string_name_value (cli_t *parser)
  {
  result_t result;
  const char * config_string_name_ = 0;
  const char * config_string_name_value_ = 0;

  if(failed(result = cli_get_string(&parser->tokens[1], &config_string_name_)))
    return result;

  if(failed(result = cli_get_string(&parser->tokens[2], &config_string_name_value_)))
    return result;

  result = config_string_name_value_action(parser, config_string_name_, config_string_name_value_);


  return result;
  }


static result_t cli_config_bool_name_value (cli_t *parser)
  {
  result_t result;
  const char * config_bool_name_ = 0;
  uint16_t config_bool_name_value_;

  if(failed(result = cli_get_string(&parser->tokens[1], &config_bool_name_)))
    return result;

  if(failed(result = cli_get_enum(&parser->tokens[2], booleans, &config_bool_name_value_)))
    return result;

  result = config_bool_name_value_action(parser, config_bool_name_, config_bool_name_value_);


  return result;
  }


static result_t cli_config_float_name_value (cli_t *parser)
  {
  result_t result;
  const char * config_float_name_ = 0;
  float config_float_name_value_;

  if(failed(result = cli_get_string(&parser->tokens[1], &config_float_name_)))
    return result;

  if(failed(result = cli_get_float(&parser->tokens[2], &config_float_name_value_)))
    return result;

  result = config_float_name_value_action(parser, config_float_name_, config_float_name_value_);


  return result;
  }


static result_t cli_config_rm_name (cli_t *parser)
  {
  result_t result;
  const char * config_rm_name_ = 0;

  if(failed(result = cli_get_string(&parser->tokens[1], &config_rm_name_)))
    return result;

  result = config_rm_name_action(parser, config_rm_name_);


  return result;
  }


static result_t cli_config_mkdir_path (cli_t *parser)
  {
  result_t result;
  const char * config_mkdir_path_ = 0;

  if(failed(result = cli_get_string(&parser->tokens[1], &config_mkdir_path_)))
    return result;

  result = config_mkdir_path_action(parser, config_mkdir_path_);


  return result;
  }


static result_t cli_config_rmdir_path (cli_t *parser)
  {
  result_t result;
  const char * config_rmdir_path_ = 0;

  if(failed(result = cli_get_string(&parser->tokens[1], &config_rmdir_path_)))
    return result;

  result = config_rmdir_path_action(parser, config_rmdir_path_);


  return result;
  }


static result_t cli_config_cd_path (cli_t *parser)
  {
  result_t result;
  const char * config_cd_path_ = 0;

  if(failed(result = cli_get_string(&parser->tokens[1], &config_cd_path_)))
    return result;

  result = config_cd_path_action(parser, config_cd_path_);


  return result;
  }


static result_t cli_config_ls_path_recursive (cli_t *parser)
  {
  result_t result;
  const char * config_ls_path_ = 0;

  if(failed(result = cli_get_string(&parser->tokens[1], &config_ls_path_)))
    return result;

  result = config_ls_path_recursive_action(parser, config_ls_path_);


  return result;
  }


static result_t cli_config_exit (cli_t *parser)
  {
  result_t result;
  result = config_exit_action(parser);


  return result;
  }


static result_t cli_config (cli_t *parser)
  {
  result_t result;
  result = config_action(parser);


  return result;
  }


static result_t cli_neutron_ls_id (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_ls_id_;

  if(parser->tokens[1].token_length > 0 &&
    failed(result = cli_get_enum(&parser->tokens[1], can_ids, &neutron_ls_id_)))
    return result;

  result = neutron_ls_id_action(parser, ((parser->tokens[1].token_length > 0) ? &neutron_ls_id_ : 0));


  return result;
  }


static result_t cli_neutron_rm_id (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_rm_id_;

  if(failed(result = cli_get_enum(&parser->tokens[1], can_ids, &neutron_rm_id_)))
    return result;

  result = neutron_rm_id_action(parser, neutron_rm_id_);


  return result;
  }


static result_t cli_neutron_publish_id_rate_rate (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_publish_id_rate_rate_;

  if(failed(result = cli_get_uint16(&parser->tokens[1], &neutron_publish_id_rate_rate_)))
    return result;

  result = neutron_publish_id_rate_rate_action(parser, neutron_publish_id_rate_rate_);


  return result;
  }


static result_t cli_neutron_publish_id_type_type (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_publish_id_type_type_;

  if(failed(result = cli_get_enum(&parser->tokens[1], publish_types, &neutron_publish_id_type_type_)))
    return result;

  result = neutron_publish_id_type_type_action(parser, neutron_publish_id_type_type_);


  return result;
  }


static result_t cli_neutron_publish_id_sample_sample (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_publish_id_sample_sample_;

  if(failed(result = cli_get_enum(&parser->tokens[1], sample_types, &neutron_publish_id_sample_sample_)))
    return result;

  result = neutron_publish_id_sample_sample_action(parser, neutron_publish_id_sample_sample_);


  return result;
  }


static result_t cli_neutron_publish_id_publish_is_published (cli_t *parser)
  {
  result_t result;
  bool neutron_publish_id_publish_is_published_;

  if(failed(result = cli_get_bool(&parser->tokens[1], booleans, &neutron_publish_id_publish_is_published_)))
    return result;

  result = neutron_publish_id_publish_is_published_action(parser, neutron_publish_id_publish_is_published_);


  return result;
  }


static result_t cli_neutron_publish_id_loopback_loopback (cli_t *parser)
  {
  result_t result;
  bool neutron_publish_id_loopback_loopback_;

  if(failed(result = cli_get_bool(&parser->tokens[1], booleans, &neutron_publish_id_loopback_loopback_)))
    return result;

  result = neutron_publish_id_loopback_loopback_action(parser, neutron_publish_id_loopback_loopback_);


  return result;
  }


static result_t cli_neutron_publish_id_filter_filter_type_length_value (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_publish_id_filter_filter_type_length_value_;

  if(failed(result = cli_get_uint16(&parser->tokens[1], &neutron_publish_id_filter_filter_type_length_value_)))
    return result;

  result = neutron_publish_id_filter_filter_type_length_value_action(parser, neutron_publish_id_filter_filter_type_length_value_);


  return result;
  }


static result_t cli_neutron_publish_id_filter_filter_type_coeff_index_value (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_publish_id_filter_filter_type_coeff_index_;
  float neutron_publish_id_filter_filter_type_coeff_index_value_;

  if(failed(result = cli_get_uint16(&parser->tokens[1], &neutron_publish_id_filter_filter_type_coeff_index_)))
    return result;

  if(failed(result = cli_get_float(&parser->tokens[2], &neutron_publish_id_filter_filter_type_coeff_index_value_)))
    return result;

  result = neutron_publish_id_filter_filter_type_coeff_index_value_action(parser, neutron_publish_id_filter_filter_type_coeff_index_, neutron_publish_id_filter_filter_type_coeff_index_value_);


  return result;
  }


static result_t cli_neutron_publish_id_filter_filter_type_gain_value (cli_t *parser)
  {
  result_t result;
  float neutron_publish_id_filter_filter_type_gain_value_;

  if(failed(result = cli_get_float(&parser->tokens[1], &neutron_publish_id_filter_filter_type_gain_value_)))
    return result;

  result = neutron_publish_id_filter_filter_type_gain_value_action(parser, neutron_publish_id_filter_filter_type_gain_value_);


  return result;
  }


static result_t cli_neutron_publish_id_filter_filter_type_exit (cli_t *parser)
  {
  result_t result;
  result = neutron_publish_id_filter_filter_type_exit_action(parser);


  return result;
  }


static result_t cli_neutron_publish_id_filter_filter_type (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_publish_id_filter_filter_type_;

  if(failed(result = cli_get_enum(&parser->tokens[1], filter_types, &neutron_publish_id_filter_filter_type_)))
    return result;

  result = neutron_publish_id_filter_filter_type_action(parser, neutron_publish_id_filter_filter_type_);


  return result;
  }


static result_t cli_neutron_publish_id_alarm_alarm_id_type_alarm_type (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_publish_id_alarm_alarm_id_type_alarm_type_;

  if(failed(result = cli_get_enum(&parser->tokens[1], alarm_types, &neutron_publish_id_alarm_alarm_id_type_alarm_type_)))
    return result;

  result = neutron_publish_id_alarm_alarm_id_type_alarm_type_action(parser, neutron_publish_id_alarm_alarm_id_type_alarm_type_);


  return result;
  }


static result_t cli_neutron_publish_id_alarm_alarm_id_period_length (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_publish_id_alarm_alarm_id_period_length_;

  if(failed(result = cli_get_uint16(&parser->tokens[1], &neutron_publish_id_alarm_alarm_id_period_length_)))
    return result;

  result = neutron_publish_id_alarm_alarm_id_period_length_action(parser, neutron_publish_id_alarm_alarm_id_period_length_);


  return result;
  }


static result_t cli_neutron_publish_id_alarm_alarm_id_max_max_value (cli_t *parser)
  {
  result_t result;
  float neutron_publish_id_alarm_alarm_id_max_max_value_;

  if(failed(result = cli_get_float(&parser->tokens[1], &neutron_publish_id_alarm_alarm_id_max_max_value_)))
    return result;

  result = neutron_publish_id_alarm_alarm_id_max_max_value_action(parser, neutron_publish_id_alarm_alarm_id_max_max_value_);


  return result;
  }


static result_t cli_neutron_publish_id_alarm_alarm_id_min_min_value (cli_t *parser)
  {
  result_t result;
  float neutron_publish_id_alarm_alarm_id_min_min_value_;

  if(failed(result = cli_get_float(&parser->tokens[1], &neutron_publish_id_alarm_alarm_id_min_min_value_)))
    return result;

  result = neutron_publish_id_alarm_alarm_id_min_min_value_action(parser, neutron_publish_id_alarm_alarm_id_min_min_value_);


  return result;
  }


static result_t cli_neutron_publish_id_alarm_alarm_id_reset_reset_id (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_publish_id_alarm_alarm_id_reset_reset_id_;

  if(failed(result = cli_get_enum(&parser->tokens[1], can_ids, &neutron_publish_id_alarm_alarm_id_reset_reset_id_)))
    return result;

  result = neutron_publish_id_alarm_alarm_id_reset_reset_id_action(parser, neutron_publish_id_alarm_alarm_id_reset_reset_id_);


  return result;
  }


static result_t cli_neutron_publish_id_alarm_alarm_id_exit (cli_t *parser)
  {
  result_t result;
  result = neutron_publish_id_alarm_alarm_id_exit_action(parser);


  return result;
  }


static result_t cli_neutron_publish_id_alarm_alarm_id (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_publish_id_alarm_alarm_id_;

  if(failed(result = cli_get_uint16(&parser->tokens[1], &neutron_publish_id_alarm_alarm_id_)))
    return result;

  result = neutron_publish_id_alarm_alarm_id_action(parser, neutron_publish_id_alarm_alarm_id_);


  return result;
  }


static result_t cli_neutron_publish_id_exit (cli_t *parser)
  {
  result_t result;
  result = neutron_publish_id_exit_action(parser);


  return result;
  }


static result_t cli_neutron_publish_id (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_publish_id_;

  if(failed(result = cli_get_enum(&parser->tokens[1], can_ids, &neutron_publish_id_)))
    return result;

  result = neutron_publish_id_action(parser, neutron_publish_id_);


  return result;
  }


static result_t cli_neutron_exit (cli_t *parser)
  {
  result_t result;
  result = neutron_exit_action(parser);


  return result;
  }


static result_t cli_neutron (cli_t *parser)
  {
  result_t result;
  result = neutron_action(parser);


  return result;
  }


static result_t cli_send_can_id_type_val1_val2_val3_val4 (cli_t *parser)
  {
  result_t result;
  uint16_t send_can_id_;
  uint16_t send_can_id_type_;
  const char * send_can_id_type_val1_ = 0;
  const char * send_can_id_type_val1_val2_ = 0;
  const char * send_can_id_type_val1_val2_val3_ = 0;
  const char * send_can_id_type_val1_val2_val3_val4_ = 0;

  if(failed(result = cli_get_enum(&parser->tokens[1], can_ids, &send_can_id_)))
    return result;

  if(failed(result = cli_get_enum(&parser->tokens[2], can_types, &send_can_id_type_)))
    return result;

  if(parser->tokens[3].token_length > 0 &&
    failed(result = cli_get_string(&parser->tokens[3], &send_can_id_type_val1_)))
    return result;

  if(parser->tokens[4].token_length > 0 &&
    failed(result = cli_get_string(&parser->tokens[4], &send_can_id_type_val1_val2_)))
    return result;

  if(parser->tokens[5].token_length > 0 &&
    failed(result = cli_get_string(&parser->tokens[5], &send_can_id_type_val1_val2_val3_)))
    return result;

  if(parser->tokens[6].token_length > 0 &&
    failed(result = cli_get_string(&parser->tokens[6], &send_can_id_type_val1_val2_val3_val4_)))
    return result;

  result = send_can_id_type_val1_val2_val3_val4_action(parser, send_can_id_, send_can_id_type_, ((parser->tokens[3].token_length > 0) ? send_can_id_type_val1_ : 0), ((parser->tokens[4].token_length > 0) ? send_can_id_type_val1_val2_ : 0), ((parser->tokens[5].token_length > 0) ? send_can_id_type_val1_val2_val3_ : 0), ((parser->tokens[6].token_length > 0) ? send_can_id_type_val1_val2_val3_val4_ : 0));


  return result;
  }


static result_t cli_recv_can_id_type_val1_val2_val3_val4 (cli_t *parser)
  {
  result_t result;
  uint16_t recv_can_id_;
  uint16_t recv_can_id_type_;
  const char * recv_can_id_type_val1_ = 0;
  const char * recv_can_id_type_val1_val2_ = 0;
  const char * recv_can_id_type_val1_val2_val3_ = 0;
  const char * recv_can_id_type_val1_val2_val3_val4_ = 0;

  if(failed(result = cli_get_enum(&parser->tokens[1], can_ids, &recv_can_id_)))
    return result;

  if(failed(result = cli_get_enum(&parser->tokens[2], can_types, &recv_can_id_type_)))
    return result;

  if(parser->tokens[3].token_length > 0 &&
    failed(result = cli_get_string(&parser->tokens[3], &recv_can_id_type_val1_)))
    return result;

  if(parser->tokens[4].token_length > 0 &&
    failed(result = cli_get_string(&parser->tokens[4], &recv_can_id_type_val1_val2_)))
    return result;

  if(parser->tokens[5].token_length > 0 &&
    failed(result = cli_get_string(&parser->tokens[5], &recv_can_id_type_val1_val2_val3_)))
    return result;

  if(parser->tokens[6].token_length > 0 &&
    failed(result = cli_get_string(&parser->tokens[6], &recv_can_id_type_val1_val2_val3_val4_)))
    return result;

  result = recv_can_id_type_val1_val2_val3_val4_action(parser, recv_can_id_, recv_can_id_type_, ((parser->tokens[3].token_length > 0) ? recv_can_id_type_val1_ : 0), ((parser->tokens[4].token_length > 0) ? recv_can_id_type_val1_val2_ : 0), ((parser->tokens[5].token_length > 0) ? recv_can_id_type_val1_val2_val3_ : 0), ((parser->tokens[6].token_length > 0) ? recv_can_id_type_val1_val2_val3_val4_ : 0));


  return result;
  }


static result_t cli_exit (cli_t *parser)
  {
  result_t result;
  result = exit_action(parser);


  return result;
  }


static cli_node_t node_config_uint8_name_value_end;

static cli_node_t node_config_uint8_name_value;

static cli_node_t node_config_uint8_name;

static cli_node_t node_config_uint8;

static cli_node_t node_config_int8_name_value_end;

static cli_node_t node_config_int8_name_value;

static cli_node_t node_config_int8_name;

static cli_node_t node_config_int8;

static cli_node_t node_config_uint16_name_value_end;

static cli_node_t node_config_uint16_name_value;

static cli_node_t node_config_uint16_name;

static cli_node_t node_config_uint16;

static cli_node_t node_config_int16_name_value_end;

static cli_node_t node_config_int16_name_value;

static cli_node_t node_config_int16_name;

static cli_node_t node_config_int16;

static cli_node_t node_config_uint32_name_value_end;

static cli_node_t node_config_uint32_name_value;

static cli_node_t node_config_uint32_name;

static cli_node_t node_config_uint32;

static cli_node_t node_config_int32_name_value_end;

static cli_node_t node_config_int32_name_value;

static cli_node_t node_config_int32_name;

static cli_node_t node_config_int32;

static cli_node_t node_config_xyz_name_value_end;

static cli_node_t node_config_xyz_name_value;

static cli_node_t node_config_xyz_name;

static cli_node_t node_config_xyz;

static cli_node_t node_config_matrix_name_value_end;

static cli_node_t node_config_matrix_name_value;

static cli_node_t node_config_matrix_name;

static cli_node_t node_config_matrix;

static cli_node_t node_config_string_name_value_end;

static cli_node_t node_config_string_name_value;

static cli_node_t node_config_string_name;

static cli_node_t node_config_string;

static cli_node_t node_config_bool_name_value_end;

static cli_node_t node_config_bool_name_value;

static cli_node_t node_config_bool_name;

static cli_node_t node_config_bool;

static cli_node_t node_config_float_name_value_end;

static cli_node_t node_config_float_name_value;

static cli_node_t node_config_float_name;

static cli_node_t node_config_float;

static cli_node_t node_config_rm_name_end;

static cli_node_t node_config_rm_name;

static cli_node_t node_config_rm;

static cli_node_t node_config_mkdir_path_end;

static cli_node_t node_config_mkdir_path;

static cli_node_t node_config_mkdir;

static cli_node_t node_config_rmdir_path_end;

static cli_node_t node_config_rmdir_path;

static cli_node_t node_config_rmdir;

static cli_node_t node_config_cd_path_end;

static cli_node_t node_config_cd_path;

static cli_node_t node_config_cd;

static cli_node_t node_config_ls_path_recursive_end;

static cli_node_t node_config_ls_path_recursive;

static cli_node_t node_config_ls_path;

static cli_node_t node_config_ls;

static cli_node_t node_config_exit_end;

static cli_node_t node_config_exit;

static cli_node_t node_config_end;

static cli_node_t node_config;

static cli_node_t node_neutron_ls_id_end;

static cli_node_t node_neutron_ls_id;

static cli_node_t node_neutron_ls;

static cli_node_t node_neutron_rm_id_end;

static cli_node_t node_neutron_rm_id;

static cli_node_t node_neutron_rm;

static cli_node_t node_neutron_publish_id_rate_rate_end;

static cli_node_t node_neutron_publish_id_rate_rate;

static cli_node_t node_neutron_publish_id_rate;

static cli_node_t node_neutron_publish_id_type_type_end;

static cli_node_t node_neutron_publish_id_type_type;

static cli_node_t node_neutron_publish_id_type;

static cli_node_t node_neutron_publish_id_sample_sample_end;

static cli_node_t node_neutron_publish_id_sample_sample;

static cli_node_t node_neutron_publish_id_sample;

static cli_node_t node_neutron_publish_id_publish_is_published_end;

static cli_node_t node_neutron_publish_id_publish_is_published;

static cli_node_t node_neutron_publish_id_publish;

static cli_node_t node_neutron_publish_id_loopback_loopback_end;

static cli_node_t node_neutron_publish_id_loopback_loopback;

static cli_node_t node_neutron_publish_id_loopback;

static cli_node_t node_neutron_publish_id_filter_filter_type_length_value_end;

static cli_node_t node_neutron_publish_id_filter_filter_type_length_value;

static cli_node_t node_neutron_publish_id_filter_filter_type_length;

static cli_node_t node_neutron_publish_id_filter_filter_type_coeff_index_value_end;

static cli_node_t node_neutron_publish_id_filter_filter_type_coeff_index_value;

static cli_node_t node_neutron_publish_id_filter_filter_type_coeff_index;

static cli_node_t node_neutron_publish_id_filter_filter_type_coeff;

static cli_node_t node_neutron_publish_id_filter_filter_type_gain_value_end;

static cli_node_t node_neutron_publish_id_filter_filter_type_gain_value;

static cli_node_t node_neutron_publish_id_filter_filter_type_gain;

static cli_node_t node_neutron_publish_id_filter_filter_type_exit_end;

static cli_node_t node_neutron_publish_id_filter_filter_type_exit;

static cli_node_t node_neutron_publish_id_filter_filter_type_end;

static cli_node_t node_neutron_publish_id_filter_filter_type;

static cli_node_t node_neutron_publish_id_filter;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_type_alarm_type_end;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_type_alarm_type;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_type;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_period_length_end;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_period_length;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_period;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_max_max_value_end;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_max_max_value;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_max;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_min_min_value_end;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_min_min_value;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_min;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_reset_reset_id_end;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_reset_reset_id;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_reset;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_exit_end;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_exit;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_end;

static cli_node_t node_neutron_publish_id_alarm_alarm_id;

static cli_node_t node_neutron_publish_id_alarm;

static cli_node_t node_neutron_publish_id_exit_end;

static cli_node_t node_neutron_publish_id_exit;

static cli_node_t node_neutron_publish_id_end;

static cli_node_t node_neutron_publish_id;

static cli_node_t node_neutron_publish;

static cli_node_t node_neutron_exit_end;

static cli_node_t node_neutron_exit;

static cli_node_t node_neutron_end;

static cli_node_t node_neutron;

static cli_node_t node_send_can_id_type_val1_val2_val3_val4_end;

static cli_node_t node_send_can_id_type_val1_val2_val3_val4;

static cli_node_t node_send_can_id_type_val1_val2_val3;

static cli_node_t node_send_can_id_type_val1_val2;

static cli_node_t node_send_can_id_type_val1;

static cli_node_t node_send_can_id_type;

static cli_node_t node_send_can_id;

static cli_node_t node_send_can;

static cli_node_t node_recv_can_id_type_val1_val2_val3_val4_end;

static cli_node_t node_recv_can_id_type_val1_val2_val3_val4;

static cli_node_t node_recv_can_id_type_val1_val2_val3;

static cli_node_t node_recv_can_id_type_val1_val2;

static cli_node_t node_recv_can_id_type_val1;

static cli_node_t node_recv_can_id_type;

static cli_node_t node_recv_can_id;

static cli_node_t node_recv_can;

static cli_node_t node_exit_end;

static cli_node_t node_exit;

static cli_node_t node_config_uint8_name_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_config_uint8_name_value,
  0,
  0,
  0
  };


static cli_node_t node_config_uint8_name_value = {
  CLI_NODE_UINT16,
  0,
  "UINT16:value",
  0,
  0,
  &node_config_uint8_name_value_end
  };


static cli_node_t node_config_uint8_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_config_uint8_name_value
  };


static cli_node_t node_config_uint8 = {
  CLI_NODE_KEYWORD,
  0,
  "uint8",
  0,
  &node_config_int8,
  &node_config_uint8_name
  };


static cli_node_t node_config_int8_name_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_config_int8_name_value,
  0,
  0,
  0
  };


static cli_node_t node_config_int8_name_value = {
  CLI_NODE_INT16,
  0,
  "INT16:value",
  0,
  0,
  &node_config_int8_name_value_end
  };


static cli_node_t node_config_int8_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_config_int8_name_value
  };


static cli_node_t node_config_int8 = {
  CLI_NODE_KEYWORD,
  0,
  "int8",
  0,
  &node_config_uint16,
  &node_config_int8_name
  };


static cli_node_t node_config_uint16_name_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_config_uint16_name_value,
  0,
  0,
  0
  };


static cli_node_t node_config_uint16_name_value = {
  CLI_NODE_UINT16,
  0,
  "UINT16:value",
  0,
  0,
  &node_config_uint16_name_value_end
  };


static cli_node_t node_config_uint16_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_config_uint16_name_value
  };


static cli_node_t node_config_uint16 = {
  CLI_NODE_KEYWORD,
  0,
  "uint16",
  0,
  &node_config_int16,
  &node_config_uint16_name
  };


static cli_node_t node_config_int16_name_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_config_int16_name_value,
  0,
  0,
  0
  };


static cli_node_t node_config_int16_name_value = {
  CLI_NODE_INT16,
  0,
  "INT16:value",
  0,
  0,
  &node_config_int16_name_value_end
  };


static cli_node_t node_config_int16_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_config_int16_name_value
  };


static cli_node_t node_config_int16 = {
  CLI_NODE_KEYWORD,
  0,
  "int16",
  0,
  &node_config_uint32,
  &node_config_int16_name
  };


static cli_node_t node_config_uint32_name_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_config_uint32_name_value,
  0,
  0,
  0
  };


static cli_node_t node_config_uint32_name_value = {
  CLI_NODE_UINT32,
  0,
  "UINT32:value",
  0,
  0,
  &node_config_uint32_name_value_end
  };


static cli_node_t node_config_uint32_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_config_uint32_name_value
  };


static cli_node_t node_config_uint32 = {
  CLI_NODE_KEYWORD,
  0,
  "uint32",
  0,
  &node_config_int32,
  &node_config_uint32_name
  };


static cli_node_t node_config_int32_name_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_config_int32_name_value,
  0,
  0,
  0
  };


static cli_node_t node_config_int32_name_value = {
  CLI_NODE_INT32,
  0,
  "INT32:value",
  0,
  0,
  &node_config_int32_name_value_end
  };


static cli_node_t node_config_int32_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_config_int32_name_value
  };


static cli_node_t node_config_int32 = {
  CLI_NODE_KEYWORD,
  0,
  "int32",
  0,
  &node_config_xyz,
  &node_config_int32_name
  };


static cli_node_t node_config_xyz_name_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_config_xyz_name_value,
  0,
  0,
  0
  };


static cli_node_t node_config_xyz_name_value = {
  CLI_NODE_XYZ,
  0,
  "XYZ:value",
  0,
  0,
  &node_config_xyz_name_value_end
  };


static cli_node_t node_config_xyz_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_config_xyz_name_value
  };


static cli_node_t node_config_xyz = {
  CLI_NODE_KEYWORD,
  0,
  "xyz",
  0,
  &node_config_matrix,
  &node_config_xyz_name
  };


static cli_node_t node_config_matrix_name_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_config_matrix_name_value,
  0,
  0,
  0
  };


static cli_node_t node_config_matrix_name_value = {
  CLI_NODE_MATRIX,
  0,
  "MATRIX:value",
  0,
  0,
  &node_config_matrix_name_value_end
  };


static cli_node_t node_config_matrix_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_config_matrix_name_value
  };


static cli_node_t node_config_matrix = {
  CLI_NODE_KEYWORD,
  0,
  "matrix",
  0,
  &node_config_string,
  &node_config_matrix_name
  };


static cli_node_t node_config_string_name_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_config_string_name_value,
  0,
  0,
  0
  };


static cli_node_t node_config_string_name_value = {
  CLI_NODE_STRING,
  0,
  "STRING:value",
  0,
  0,
  &node_config_string_name_value_end
  };


static cli_node_t node_config_string_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_config_string_name_value
  };


static cli_node_t node_config_string = {
  CLI_NODE_KEYWORD,
  0,
  "string",
  0,
  &node_config_bool,
  &node_config_string_name
  };


static cli_node_t node_config_bool_name_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_config_bool_name_value,
  0,
  0,
  0
  };


static cli_node_t node_config_bool_name_value = {
  CLI_NODE_ENUM,
  0,
  &booleans,
  0,
  0,
  &node_config_bool_name_value_end
  };


static cli_node_t node_config_bool_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_config_bool_name_value
  };


static cli_node_t node_config_bool = {
  CLI_NODE_KEYWORD,
  0,
  "bool",
  0,
  &node_config_float,
  &node_config_bool_name
  };


static cli_node_t node_config_float_name_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_config_float_name_value,
  0,
  0,
  0
  };


static cli_node_t node_config_float_name_value = {
  CLI_NODE_FLOAT,
  0,
  "FLOAT:value",
  0,
  0,
  &node_config_float_name_value_end
  };


static cli_node_t node_config_float_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_config_float_name_value
  };


static cli_node_t node_config_float = {
  CLI_NODE_KEYWORD,
  0,
  "float",
  0,
  &node_config_rm,
  &node_config_float_name
  };


static cli_node_t node_config_rm_name_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_config_rm_name,
  0,
  0,
  0
  };


static cli_node_t node_config_rm_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_config_rm_name_end
  };


static cli_node_t node_config_rm = {
  CLI_NODE_KEYWORD,
  0,
  "rm",
  0,
  &node_config_mkdir,
  &node_config_rm_name
  };


static cli_node_t node_config_mkdir_path_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_config_mkdir_path,
  0,
  0,
  0
  };


static cli_node_t node_config_mkdir_path = {
  CLI_NODE_STRING,
  0,
  "STRING:path",
  0,
  0,
  &node_config_mkdir_path_end
  };


static cli_node_t node_config_mkdir = {
  CLI_NODE_KEYWORD,
  0,
  "mkdir",
  0,
  &node_config_rmdir,
  &node_config_mkdir_path
  };


static cli_node_t node_config_rmdir_path_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_config_rmdir_path,
  0,
  0,
  0
  };


static cli_node_t node_config_rmdir_path = {
  CLI_NODE_STRING,
  0,
  "STRING:path",
  0,
  0,
  &node_config_rmdir_path_end
  };


static cli_node_t node_config_rmdir = {
  CLI_NODE_KEYWORD,
  0,
  "rmdir",
  0,
  &node_config_cd,
  &node_config_rmdir_path
  };


static cli_node_t node_config_cd_path_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_config_cd_path,
  0,
  0,
  0
  };


static cli_node_t node_config_cd_path = {
  CLI_NODE_STRING,
  0,
  "STRING:path",
  0,
  0,
  &node_config_cd_path_end
  };


static cli_node_t node_config_cd = {
  CLI_NODE_KEYWORD,
  0,
  "cd",
  0,
  &node_config_ls,
  &node_config_cd_path
  };


static cli_node_t node_config_ls_path_recursive_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_config_ls_path_recursive,
  0,
  0,
  0
  };


static cli_node_t node_config_ls_path_recursive = {
  CLI_NODE_KEYWORD,
  CLI_NODE_FLAGS_OPT_START | CLI_NODE_FLAGS_OPT_END | CLI_NODE_FLAGS_OPT_PARTIAL,
  "recursive",
  0,
  0,
  &node_config_ls_path_recursive_end
  };


static cli_node_t node_config_ls_path = {
  CLI_NODE_STRING,
  0,
  "STRING:path",
  0,
  0,
  &node_config_ls_path_recursive
  };


static cli_node_t node_config_ls = {
  CLI_NODE_KEYWORD,
  0,
  "ls",
  0,
  &node_config_exit,
  &node_config_ls_path
  };


static cli_node_t node_config_exit_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_config_exit,
  0,
  0,
  0
  };


static cli_node_t node_config_exit = {
  CLI_NODE_KEYWORD,
  0,
  "exit",
  0,
  0,
  &node_config_exit_end
  };


static cli_node_t node_config_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_config,
  0,
  0,
  &node_config_uint8
  };


static cli_node_t node_config = {
  CLI_NODE_KEYWORD,
  0,
  "config",
  0,
  &node_neutron,
  &node_config_end
  };


static cli_node_t node_neutron_ls_id_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_ls_id,
  0,
  0,
  0
  };


static cli_node_t node_neutron_ls_id = {
  CLI_NODE_ENUM,
  CLI_NODE_FLAGS_OPT_START | CLI_NODE_FLAGS_OPT_END | CLI_NODE_FLAGS_OPT_PARTIAL,
  &can_ids,
  0,
  0,
  &node_neutron_ls_id_end
  };


static cli_node_t node_neutron_ls = {
  CLI_NODE_KEYWORD,
  0,
  "ls",
  0,
  &node_neutron_rm,
  &node_neutron_ls_id
  };


static cli_node_t node_neutron_rm_id_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_rm_id,
  0,
  0,
  0
  };


static cli_node_t node_neutron_rm_id = {
  CLI_NODE_ENUM,
  0,
  &can_ids,
  0,
  0,
  &node_neutron_rm_id_end
  };


static cli_node_t node_neutron_rm = {
  CLI_NODE_KEYWORD,
  0,
  "rm",
  0,
  &node_neutron_publish,
  &node_neutron_rm_id
  };


static cli_node_t node_neutron_publish_id_rate_rate_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_rate_rate,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_rate_rate = {
  CLI_NODE_UINT16,
  0,
  "UINT16:rate",
  0,
  0,
  &node_neutron_publish_id_rate_rate_end
  };


static cli_node_t node_neutron_publish_id_rate = {
  CLI_NODE_KEYWORD,
  0,
  "rate",
  0,
  &node_neutron_publish_id_type,
  &node_neutron_publish_id_rate_rate
  };


static cli_node_t node_neutron_publish_id_type_type_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_type_type,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_type_type = {
  CLI_NODE_ENUM,
  0,
  &publish_types,
  0,
  0,
  &node_neutron_publish_id_type_type_end
  };


static cli_node_t node_neutron_publish_id_type = {
  CLI_NODE_KEYWORD,
  0,
  "type",
  0,
  &node_neutron_publish_id_sample,
  &node_neutron_publish_id_type_type
  };


static cli_node_t node_neutron_publish_id_sample_sample_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_sample_sample,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_sample_sample = {
  CLI_NODE_ENUM,
  0,
  &sample_types,
  0,
  0,
  &node_neutron_publish_id_sample_sample_end
  };


static cli_node_t node_neutron_publish_id_sample = {
  CLI_NODE_KEYWORD,
  0,
  "sample",
  0,
  &node_neutron_publish_id_publish,
  &node_neutron_publish_id_sample_sample
  };


static cli_node_t node_neutron_publish_id_publish_is_published_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_publish_is_published,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_publish_is_published = {
  CLI_NODE_ENUM,
  0,
  &booleans,
  0,
  0,
  &node_neutron_publish_id_publish_is_published_end
  };


static cli_node_t node_neutron_publish_id_publish = {
  CLI_NODE_KEYWORD,
  0,
  "publish",
  0,
  &node_neutron_publish_id_loopback,
  &node_neutron_publish_id_publish_is_published
  };


static cli_node_t node_neutron_publish_id_loopback_loopback_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_loopback_loopback,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_loopback_loopback = {
  CLI_NODE_ENUM,
  0,
  &booleans,
  0,
  0,
  &node_neutron_publish_id_loopback_loopback_end
  };


static cli_node_t node_neutron_publish_id_loopback = {
  CLI_NODE_KEYWORD,
  0,
  "loopback",
  0,
  &node_neutron_publish_id_filter,
  &node_neutron_publish_id_loopback_loopback
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_length_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_filter_filter_type_length_value,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_length_value = {
  CLI_NODE_UINT16,
  0,
  "UINT16:value",
  0,
  0,
  &node_neutron_publish_id_filter_filter_type_length_value_end
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_length = {
  CLI_NODE_KEYWORD,
  0,
  "length",
  0,
  &node_neutron_publish_id_filter_filter_type_coeff,
  &node_neutron_publish_id_filter_filter_type_length_value
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_coeff_index_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_filter_filter_type_coeff_index_value,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_coeff_index_value = {
  CLI_NODE_FLOAT,
  0,
  "FLOAT:value",
  0,
  0,
  &node_neutron_publish_id_filter_filter_type_coeff_index_value_end
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_coeff_index = {
  CLI_NODE_UINT16,
  0,
  "UINT16:index",
  0,
  0,
  &node_neutron_publish_id_filter_filter_type_coeff_index_value
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_coeff = {
  CLI_NODE_KEYWORD,
  0,
  "coeff",
  0,
  &node_neutron_publish_id_filter_filter_type_gain,
  &node_neutron_publish_id_filter_filter_type_coeff_index
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_gain_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_filter_filter_type_gain_value,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_gain_value = {
  CLI_NODE_FLOAT,
  0,
  "FLOAT:value",
  0,
  0,
  &node_neutron_publish_id_filter_filter_type_gain_value_end
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_gain = {
  CLI_NODE_KEYWORD,
  0,
  "gain",
  0,
  &node_neutron_publish_id_filter_filter_type_exit,
  &node_neutron_publish_id_filter_filter_type_gain_value
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_exit_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_filter_filter_type_exit,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_exit = {
  CLI_NODE_KEYWORD,
  0,
  "exit",
  0,
  0,
  &node_neutron_publish_id_filter_filter_type_exit_end
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_filter_filter_type,
  0,
  0,
  &node_neutron_publish_id_filter_filter_type_length
  };


static cli_node_t node_neutron_publish_id_filter_filter_type = {
  CLI_NODE_ENUM,
  0,
  &filter_types,
  0,
  0,
  &node_neutron_publish_id_filter_filter_type_end
  };


static cli_node_t node_neutron_publish_id_filter = {
  CLI_NODE_KEYWORD,
  0,
  "filter",
  0,
  &node_neutron_publish_id_alarm,
  &node_neutron_publish_id_filter_filter_type
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_type_alarm_type_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_alarm_alarm_id_type_alarm_type,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_type_alarm_type = {
  CLI_NODE_ENUM,
  0,
  &alarm_types,
  0,
  0,
  &node_neutron_publish_id_alarm_alarm_id_type_alarm_type_end
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_type = {
  CLI_NODE_KEYWORD,
  0,
  "type",
  0,
  &node_neutron_publish_id_alarm_alarm_id_period,
  &node_neutron_publish_id_alarm_alarm_id_type_alarm_type
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_period_length_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_alarm_alarm_id_period_length,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_period_length = {
  CLI_NODE_UINT16,
  0,
  "UINT16:length",
  0,
  0,
  &node_neutron_publish_id_alarm_alarm_id_period_length_end
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_period = {
  CLI_NODE_KEYWORD,
  0,
  "period",
  0,
  &node_neutron_publish_id_alarm_alarm_id_max,
  &node_neutron_publish_id_alarm_alarm_id_period_length
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_max_max_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_alarm_alarm_id_max_max_value,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_max_max_value = {
  CLI_NODE_FLOAT,
  0,
  "FLOAT:max_value",
  0,
  0,
  &node_neutron_publish_id_alarm_alarm_id_max_max_value_end
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_max = {
  CLI_NODE_KEYWORD,
  0,
  "max",
  0,
  &node_neutron_publish_id_alarm_alarm_id_min,
  &node_neutron_publish_id_alarm_alarm_id_max_max_value
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_min_min_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_alarm_alarm_id_min_min_value,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_min_min_value = {
  CLI_NODE_FLOAT,
  0,
  "FLOAT:min_value",
  0,
  0,
  &node_neutron_publish_id_alarm_alarm_id_min_min_value_end
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_min = {
  CLI_NODE_KEYWORD,
  0,
  "min",
  0,
  &node_neutron_publish_id_alarm_alarm_id_reset,
  &node_neutron_publish_id_alarm_alarm_id_min_min_value
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_reset_reset_id_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_alarm_alarm_id_reset_reset_id,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_reset_reset_id = {
  CLI_NODE_ENUM,
  0,
  &can_ids,
  0,
  0,
  &node_neutron_publish_id_alarm_alarm_id_reset_reset_id_end
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_reset = {
  CLI_NODE_KEYWORD,
  0,
  "reset",
  0,
  &node_neutron_publish_id_alarm_alarm_id_exit,
  &node_neutron_publish_id_alarm_alarm_id_reset_reset_id
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_exit_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_alarm_alarm_id_exit,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_exit = {
  CLI_NODE_KEYWORD,
  0,
  "exit",
  0,
  0,
  &node_neutron_publish_id_alarm_alarm_id_exit_end
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_alarm_alarm_id,
  0,
  0,
  &node_neutron_publish_id_alarm_alarm_id_type
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id = {
  CLI_NODE_UINT16,
  0,
  "UINT16:alarm_id",
  0,
  0,
  &node_neutron_publish_id_alarm_alarm_id_end
  };


static cli_node_t node_neutron_publish_id_alarm = {
  CLI_NODE_KEYWORD,
  0,
  "alarm",
  0,
  &node_neutron_publish_id_exit,
  &node_neutron_publish_id_alarm_alarm_id
  };


static cli_node_t node_neutron_publish_id_exit_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_exit,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_exit = {
  CLI_NODE_KEYWORD,
  0,
  "exit",
  0,
  0,
  &node_neutron_publish_id_exit_end
  };


static cli_node_t node_neutron_publish_id_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id,
  0,
  0,
  &node_neutron_publish_id_rate
  };


static cli_node_t node_neutron_publish_id = {
  CLI_NODE_ENUM,
  0,
  &can_ids,
  0,
  0,
  &node_neutron_publish_id_end
  };


static cli_node_t node_neutron_publish = {
  CLI_NODE_KEYWORD,
  0,
  "publish",
  0,
  &node_neutron_exit,
  &node_neutron_publish_id
  };


static cli_node_t node_neutron_exit_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_exit,
  0,
  0,
  0
  };


static cli_node_t node_neutron_exit = {
  CLI_NODE_KEYWORD,
  0,
  "exit",
  0,
  0,
  &node_neutron_exit_end
  };


static cli_node_t node_neutron_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron,
  0,
  0,
  &node_neutron_ls
  };


static cli_node_t node_neutron = {
  CLI_NODE_KEYWORD,
  0,
  "neutron",
  0,
  &node_send_can,
  &node_neutron_end
  };


static cli_node_t node_send_can_id_type_val1_val2_val3_val4_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_send_can_id_type_val1_val2_val3_val4,
  0,
  0,
  0
  };


static cli_node_t node_send_can_id_type_val1_val2_val3_val4 = {
  CLI_NODE_STRING,
  CLI_NODE_FLAGS_OPT_START | CLI_NODE_FLAGS_OPT_END | CLI_NODE_FLAGS_OPT_PARTIAL,
  "STRING:val4",
  0,
  0,
  &node_send_can_id_type_val1_val2_val3_val4_end
  };


static cli_node_t node_send_can_id_type_val1_val2_val3 = {
  CLI_NODE_STRING,
  CLI_NODE_FLAGS_OPT_START | CLI_NODE_FLAGS_OPT_PARTIAL,
  "STRING:val3",
  0,
  0,
  &node_send_can_id_type_val1_val2_val3_val4
  };


static cli_node_t node_send_can_id_type_val1_val2 = {
  CLI_NODE_STRING,
  CLI_NODE_FLAGS_OPT_START | CLI_NODE_FLAGS_OPT_PARTIAL,
  "STRING:val2",
  0,
  0,
  &node_send_can_id_type_val1_val2_val3
  };


static cli_node_t node_send_can_id_type_val1 = {
  CLI_NODE_STRING,
  CLI_NODE_FLAGS_OPT_START | CLI_NODE_FLAGS_OPT_PARTIAL,
  "STRING:val1",
  0,
  0,
  &node_send_can_id_type_val1_val2
  };


static cli_node_t node_send_can_id_type = {
  CLI_NODE_ENUM,
  0,
  &can_types,
  0,
  0,
  &node_send_can_id_type_val1
  };


static cli_node_t node_send_can_id = {
  CLI_NODE_ENUM,
  0,
  &can_ids,
  0,
  0,
  &node_send_can_id_type
  };


static cli_node_t node_send_can = {
  CLI_NODE_KEYWORD,
  0,
  "send_can",
  0,
  &node_recv_can,
  &node_send_can_id
  };


static cli_node_t node_recv_can_id_type_val1_val2_val3_val4_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_recv_can_id_type_val1_val2_val3_val4,
  0,
  0,
  0
  };


static cli_node_t node_recv_can_id_type_val1_val2_val3_val4 = {
  CLI_NODE_STRING,
  CLI_NODE_FLAGS_OPT_START | CLI_NODE_FLAGS_OPT_END | CLI_NODE_FLAGS_OPT_PARTIAL,
  "STRING:val4",
  0,
  0,
  &node_recv_can_id_type_val1_val2_val3_val4_end
  };


static cli_node_t node_recv_can_id_type_val1_val2_val3 = {
  CLI_NODE_STRING,
  CLI_NODE_FLAGS_OPT_START | CLI_NODE_FLAGS_OPT_PARTIAL,
  "STRING:val3",
  0,
  0,
  &node_recv_can_id_type_val1_val2_val3_val4
  };


static cli_node_t node_recv_can_id_type_val1_val2 = {
  CLI_NODE_STRING,
  CLI_NODE_FLAGS_OPT_START | CLI_NODE_FLAGS_OPT_PARTIAL,
  "STRING:val2",
  0,
  0,
  &node_recv_can_id_type_val1_val2_val3
  };


static cli_node_t node_recv_can_id_type_val1 = {
  CLI_NODE_STRING,
  CLI_NODE_FLAGS_OPT_START | CLI_NODE_FLAGS_OPT_PARTIAL,
  "STRING:val1",
  0,
  0,
  &node_recv_can_id_type_val1_val2
  };


static cli_node_t node_recv_can_id_type = {
  CLI_NODE_ENUM,
  0,
  &can_types,
  0,
  0,
  &node_recv_can_id_type_val1
  };


static cli_node_t node_recv_can_id = {
  CLI_NODE_ENUM,
  0,
  &can_ids,
  0,
  0,
  &node_recv_can_id_type
  };


static cli_node_t node_recv_can = {
  CLI_NODE_KEYWORD,
  0,
  "recv_can",
  0,
  &node_exit,
  &node_recv_can_id
  };


static cli_node_t node_exit_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_exit,
  0,
  0,
  0
  };


static cli_node_t node_exit = {
  CLI_NODE_KEYWORD,
  0,
  "exit",
  0,
  0,
  &node_exit_end
  };


cli_node_t kedm_cli_root = {
  CLI_NODE_ROOT,
  0,
  0,
  "Root node of the parser tree",
  0,
  &node_config
  };


