#include "./gluon_cli.h"
/* This file is generated by cli */

result_t gluon_ls_name_action(cli_t *context, const char * gluon_ls_name_)
  {
  return e_not_implemented;
  }



result_t gluon_rm_name_action(cli_t *context, const char * gluon_rm_name_)
  {
  return e_not_implemented;
  }



result_t gluon_capture_name_rate_rate_action(cli_t *context, uint16_t gluon_capture_name_rate_rate_)
  {
  return e_not_implemented;
  }



result_t gluon_capture_name_length_length_action(cli_t *context, uint32_t gluon_capture_name_length_length_)
  {
  return e_not_implemented;
  }



result_t gluon_capture_name_trigger_eq_id_value_action(cli_t *context, uint16_t gluon_capture_name_trigger_eq_id_, int16_t gluon_capture_name_trigger_eq_id_value_)
  {
  return e_not_implemented;
  }



result_t gluon_capture_name_trigger_lt_id_value_action(cli_t *context, uint16_t gluon_capture_name_trigger_lt_id_, int16_t gluon_capture_name_trigger_lt_id_value_)
  {
  return e_not_implemented;
  }



result_t gluon_capture_name_trigger_gt_id_value_action(cli_t *context, uint16_t gluon_capture_name_trigger_gt_id_, int16_t gluon_capture_name_trigger_gt_id_value_)
  {
  return e_not_implemented;
  }



result_t gluon_capture_name_trigger_eqf_id_value_action(cli_t *context, uint16_t gluon_capture_name_trigger_eqf_id_, float gluon_capture_name_trigger_eqf_id_value_)
  {
  return e_not_implemented;
  }



result_t gluon_capture_name_trigger_ltf_id_value_action(cli_t *context, uint16_t gluon_capture_name_trigger_ltf_id_, float gluon_capture_name_trigger_ltf_id_value_)
  {
  return e_not_implemented;
  }



result_t gluon_capture_name_trigger_gtf_id_value_action(cli_t *context, uint16_t gluon_capture_name_trigger_gtf_id_, float gluon_capture_name_trigger_gtf_id_value_)
  {
  return e_not_implemented;
  }



result_t gluon_capture_name_trigger_rm_eq_id_action(cli_t *context, uint16_t gluon_capture_name_trigger_rm_eq_id_)
  {
  return e_not_implemented;
  }



result_t gluon_capture_name_trigger_rm_lt_id_action(cli_t *context, uint16_t gluon_capture_name_trigger_rm_lt_id_)
  {
  return e_not_implemented;
  }



result_t gluon_capture_name_trigger_rm_gt_id_action(cli_t *context, uint16_t gluon_capture_name_trigger_rm_gt_id_)
  {
  return e_not_implemented;
  }



result_t gluon_capture_name_trigger_rm_eqf_id_action(cli_t *context, uint16_t gluon_capture_name_trigger_rm_eqf_id_)
  {
  return e_not_implemented;
  }



result_t gluon_capture_name_trigger_rm_ltf_id_action(cli_t *context, uint16_t gluon_capture_name_trigger_rm_ltf_id_)
  {
  return e_not_implemented;
  }



result_t gluon_capture_name_trigger_rm_gtf_id_action(cli_t *context, uint16_t gluon_capture_name_trigger_rm_gtf_id_)
  {
  return e_not_implemented;
  }



result_t gluon_capture_name_trigger_exit_action(cli_t *context)
  {
  return e_not_implemented;
  }



result_t gluon_capture_name_trigger_action(cli_t *context)
  {
  return e_not_implemented;
  }



result_t gluon_capture_name_ls_action(cli_t *context)
  {
  return e_not_implemented;
  }



result_t gluon_capture_name_id_id_name_action(cli_t *context, uint16_t gluon_capture_name_id_id_, const char * gluon_capture_name_id_id_name_)
  {
  return e_not_implemented;
  }



result_t gluon_capture_name_rm_id_action(cli_t *context, uint16_t gluon_capture_name_rm_id_)
  {
  return e_not_implemented;
  }



result_t gluon_capture_name_exit_action(cli_t *context)
  {
  return e_not_implemented;
  }



result_t gluon_capture_name_action(cli_t *context, const char * gluon_capture_name_)
  {
  return e_not_implemented;
  }



result_t gluon_exit_action(cli_t *context)
  {
  return e_not_implemented;
  }



result_t gluon_action(cli_t *context)
  {
  return e_not_implemented;
  }



