//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#ifndef _CANFLY_PHOTON_H_
#define _CANFLY_PHOTON_H_

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>
#include <nanoPackStruct.h>

typedef enum __nfpack PenStyle
{
    PenStyle_Solid = 0,
    PenStyle_Dash = 1,
    PenStyle_Dot = 2,
    PenStyle_DashDot = 3,
    PenStyle_DashDotDot = 4,
    PenStyle_Null = 5,
} PenStyle;

typedef enum __nfpack TextOutStyle
{
    TextOutStyle_Clipped = 2,
    TextOutStyle_Opaque = 4,
} TextOutStyle;

struct Library_CanFly_Photon_CanFly_Colors
{
    static const int FIELD_STATIC__White = 0;
    static const int FIELD_STATIC__Black = 1;
    static const int FIELD_STATIC__Gray = 2;
    static const int FIELD_STATIC__LightGray = 3;
    static const int FIELD_STATIC__DarkGray = 4;
    static const int FIELD_STATIC__Red = 5;
    static const int FIELD_STATIC__Pink = 6;
    static const int FIELD_STATIC__Blue = 7;
    static const int FIELD_STATIC__Green = 8;
    static const int FIELD_STATIC__LightGreen = 9;
    static const int FIELD_STATIC__Yellow = 10;
    static const int FIELD_STATIC__Magenta = 11;
    static const int FIELD_STATIC__Cyan = 12;
    static const int FIELD_STATIC__PaleYellow = 13;
    static const int FIELD_STATIC__LightYellow = 14;
    static const int FIELD_STATIC__LimeGreen = 15;
    static const int FIELD_STATIC__Teal = 16;
    static const int FIELD_STATIC__DarkGreen = 17;
    static const int FIELD_STATIC__Maroon = 18;
    static const int FIELD_STATIC__Purple = 19;
    static const int FIELD_STATIC__Orange = 20;
    static const int FIELD_STATIC__Khaki = 21;
    static const int FIELD_STATIC__Olive = 22;
    static const int FIELD_STATIC__Brown = 23;
    static const int FIELD_STATIC__Navy = 24;
    static const int FIELD_STATIC__LightBlue = 25;
    static const int FIELD_STATIC__FadedBlue = 26;
    static const int FIELD_STATIC__LightGrey = 27;
    static const int FIELD_STATIC__DarkGrey = 28;
    static const int FIELD_STATIC__Hollow = 29;

    //--//

};

struct Library_CanFly_Photon_CanFly_Extent
{
    static const int FIELD___dx = 1;
    static const int FIELD___dy = 2;

    //--//

};

struct Library_CanFly_Photon_CanFly_Font
{
    static const int FIELD___hndl = 1;

    //--//

};

struct Library_CanFly_Photon_CanFly_Point
{
    static const int FIELD___x = 1;
    static const int FIELD___y = 2;

    //--//

};

struct Library_CanFly_Photon_CanFly_Rect
{
    static const int FIELD___left = 1;
    static const int FIELD___top = 2;
    static const int FIELD___right = 3;
    static const int FIELD___bottom = 4;

    //--//

};

struct Library_CanFly_Photon_CanFly_GdiObject
{
    static const int FIELD___hndl = 1;
    static const int FIELD___clip_rect = 2;

    //--//

};

struct Library_CanFly_Photon_CanFly_Pen
{
    static const int FIELD___handle = 1;

    //--//

};

struct Library_CanFly_Photon_CanFly_PhotonID
{
    static const int FIELD_STATIC__id_photon = 30;
    static const int FIELD_STATIC__id_paint = 31;
    static const int FIELD_STATIC__id_timer = 32;
    static const int FIELD_STATIC__id_key0 = 33;
    static const int FIELD_STATIC__id_key1 = 34;
    static const int FIELD_STATIC__id_key2 = 35;
    static const int FIELD_STATIC__id_key3 = 36;
    static const int FIELD_STATIC__id_key4 = 37;
    static const int FIELD_STATIC__id_key5 = 38;
    static const int FIELD_STATIC__id_key6 = 39;
    static const int FIELD_STATIC__id_key7 = 40;
    static const int FIELD_STATIC__id_decka = 41;
    static const int FIELD_STATIC__id_deckb = 42;
    static const int FIELD_STATIC__id_menu_up = 43;
    static const int FIELD_STATIC__id_menu_dn = 44;
    static const int FIELD_STATIC__id_menu_left = 45;
    static const int FIELD_STATIC__id_menu_right = 46;
    static const int FIELD_STATIC__id_menu_ok = 47;
    static const int FIELD_STATIC__id_menu_cancel = 48;
    static const int FIELD_STATIC__id_menu_select = 49;
    static const int FIELD_STATIC__id_buttonpress = 50;
    static const int FIELD_STATIC__id_cancel = 51;

    //--//

};

struct Library_CanFly_Photon_CanFly_PointArray
{
    static const int FIELD___handle = 1;

    //--//

};

struct Library_CanFly_Photon_CanFly_PointArray__PointEnumerator
{
    static const int FIELD___outer = 1;
    static const int FIELD___index = 2;

    //--//

};

struct Library_CanFly_Photon_CanFly_Screen
{
    static const int FIELD_STATIC___screen = 52;
    static const int FIELD_STATIC__widgetLock = 53;

    //--//

};

struct Library_CanFly_Photon_CanFly_Stream
{
    static const int FIELD___handle = 1;

    //--//

};

struct Library_CanFly_Photon_CanFly_Widget__EventInfo
{
    static const int FIELD__eventID = 1;
    static const int FIELD__handler = 2;

    //--//

};

struct Library_CanFly_Photon_CanFly_Widget
{
    static const int FIELD_STATIC__eventInfoTable = 54;

    static const int FIELD__threadSpawn = 3;
    static const int FIELD__BeforePaint = 4;
    static const int FIELD__AfterPaint = 5;

    NANOCLR_NATIVE_DECLARE(_cctor___STATIC__VOID);
    NANOCLR_NATIVE_DECLARE(AddEvent___STATIC__VOID__U4__U2);

    //--//

};

extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_CanFly_Photon;

#endif  //_CANFLY_PHOTON_H_
