#include "ion_cli.h"
/* This file is generated by cli */

result_t cli_uint16_name_value (cli_t *parser)
  {
  result_t result;
  string_t uint16_name_ = 0;
  uint16_t uint16_name_value_;

  if(failed(result = cli_get_string(&parser->tokens[1], &uint16_name_)))
    return result;

  if(failed(result = cli_get_uint16(&parser->tokens[2], &uint16_name_value_)))
    return result;

  result = uint16_name_value_action(parser, uint16_name_, uint16_name_value_);


  return result;
  }


result_t cli_int16_name_value (cli_t *parser)
  {
  result_t result;
  string_t int16_name_ = 0;
  int16_t int16_name_value_;

  if(failed(result = cli_get_string(&parser->tokens[1], &int16_name_)))
    return result;

  if(failed(result = cli_get_int16(&parser->tokens[2], &int16_name_value_)))
    return result;

  result = int16_name_value_action(parser, int16_name_, int16_name_value_);


  return result;
  }


result_t cli_uint32_name_value (cli_t *parser)
  {
  result_t result;
  string_t uint32_name_ = 0;
  uint32_t uint32_name_value_;

  if(failed(result = cli_get_string(&parser->tokens[1], &uint32_name_)))
    return result;

  if(failed(result = cli_get_uint32(&parser->tokens[2], &uint32_name_value_)))
    return result;

  result = uint32_name_value_action(parser, uint32_name_, uint32_name_value_);


  return result;
  }


result_t cli_int32_name_value (cli_t *parser)
  {
  result_t result;
  string_t int32_name_ = 0;
  int32_t int32_name_value_;

  if(failed(result = cli_get_string(&parser->tokens[1], &int32_name_)))
    return result;

  if(failed(result = cli_get_int32(&parser->tokens[2], &int32_name_value_)))
    return result;

  result = int32_name_value_action(parser, int32_name_, int32_name_value_);


  return result;
  }


result_t cli_xyz_name_value (cli_t *parser)
  {
  result_t result;
  string_t xyz_name_ = 0;
  xyz_t xyz_name_value_;

  if(failed(result = cli_get_string(&parser->tokens[1], &xyz_name_)))
    return result;

  if(failed(result = cli_get_xyz(&parser->tokens[2], &xyz_name_value_)))
    return result;

  result = xyz_name_value_action(parser, xyz_name_, &xyz_name_value_);


  return result;
  }


result_t cli_matrix_name_value (cli_t *parser)
  {
  result_t result;
  string_t matrix_name_ = 0;
  matrix_t matrix_name_value_;

  if(failed(result = cli_get_string(&parser->tokens[1], &matrix_name_)))
    return result;

  if(failed(result = cli_get_matrix(&parser->tokens[2], &matrix_name_value_)))
    return result;

  result = matrix_name_value_action(parser, matrix_name_, &matrix_name_value_);


  return result;
  }


result_t cli_string_name_value (cli_t *parser)
  {
  result_t result;
  string_t string_name_ = 0;
  string_t string_name_value_ = 0;

  if(failed(result = cli_get_string(&parser->tokens[1], &string_name_)))
    return result;

  if(failed(result = cli_get_string(&parser->tokens[2], &string_name_value_)))
    return result;

  result = string_name_value_action(parser, string_name_, string_name_value_);


  return result;
  }


result_t cli_bool_name_value (cli_t *parser)
  {
  result_t result;
  string_t bool_name_ = 0;
  uint16_t bool_name_value_;

  if(failed(result = cli_get_string(&parser->tokens[1], &bool_name_)))
    return result;

  if(failed(result = cli_get_enum(&parser->tokens[2], booleans, &bool_name_value_)))
    return result;

  result = bool_name_value_action(parser, bool_name_, bool_name_value_);


  return result;
  }


result_t cli_float_name_value (cli_t *parser)
  {
  result_t result;
  string_t float_name_ = 0;
  float float_name_value_;

  if(failed(result = cli_get_string(&parser->tokens[1], &float_name_)))
    return result;

  if(failed(result = cli_get_float(&parser->tokens[2], &float_name_value_)))
    return result;

  result = float_name_value_action(parser, float_name_, float_name_value_);


  return result;
  }


result_t cli_edit_name (cli_t *parser)
  {
  result_t result;
  string_t edit_name_ = 0;

  if(failed(result = cli_get_string(&parser->tokens[1], &edit_name_)))
    return result;

  result = edit_name_action(parser, edit_name_);


  return result;
  }


result_t cli_cat_name (cli_t *parser)
  {
  result_t result;
  string_t cat_name_ = 0;

  if(failed(result = cli_get_string(&parser->tokens[1], &cat_name_)))
    return result;

  result = cat_name_action(parser, cat_name_);


  return result;
  }


result_t cli_rm_name (cli_t *parser)
  {
  result_t result;
  string_t rm_name_ = 0;

  if(failed(result = cli_get_string(&parser->tokens[1], &rm_name_)))
    return result;

  result = rm_name_action(parser, rm_name_);


  return result;
  }


result_t cli_mkdir_path (cli_t *parser)
  {
  result_t result;
  string_t mkdir_path_ = 0;

  if(failed(result = cli_get_string(&parser->tokens[1], &mkdir_path_)))
    return result;

  result = mkdir_path_action(parser, mkdir_path_);


  return result;
  }


result_t cli_rmdir_path (cli_t *parser)
  {
  result_t result;
  string_t rmdir_path_ = 0;

  if(failed(result = cli_get_string(&parser->tokens[1], &rmdir_path_)))
    return result;

  result = rmdir_path_action(parser, rmdir_path_);


  return result;
  }


result_t cli_cd_path (cli_t *parser)
  {
  result_t result;
  string_t cd_path_ = 0;

  if(failed(result = cli_get_string(&parser->tokens[1], &cd_path_)))
    return result;

  result = cd_path_action(parser, cd_path_);


  return result;
  }


result_t cli_ls_path_recursive (cli_t *parser)
  {
  result_t result;
  string_t ls_path_ = 0;

  if(failed(result = cli_get_string(&parser->tokens[1], &ls_path_)))
    return result;

  result = ls_path_recursive_action(parser, ls_path_);


  return result;
  }


result_t cli_neutron_ls_id (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_ls_id_;

  if(string_length(parser->tokens[1].buffer) > 0 &&
    failed(result = cli_get_enum(&parser->tokens[1], can_ids, &neutron_ls_id_)))
    return result;

  result = neutron_ls_id_action(parser, ((string_length(parser->tokens[1].buffer) > 0) ? &neutron_ls_id_ : 0));


  return result;
  }


result_t cli_neutron_rm_id (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_rm_id_;

  if(failed(result = cli_get_enum(&parser->tokens[1], can_ids, &neutron_rm_id_)))
    return result;

  result = neutron_rm_id_action(parser, neutron_rm_id_);


  return result;
  }


result_t cli_neutron_publish_id_rate_rate (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_publish_id_rate_rate_;

  if(failed(result = cli_get_uint16(&parser->tokens[1], &neutron_publish_id_rate_rate_)))
    return result;

  result = neutron_publish_id_rate_rate_action(parser, neutron_publish_id_rate_rate_);


  return result;
  }


result_t cli_neutron_publish_id_type_type (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_publish_id_type_type_;

  if(failed(result = cli_get_enum(&parser->tokens[1], publish_types, &neutron_publish_id_type_type_)))
    return result;

  result = neutron_publish_id_type_type_action(parser, neutron_publish_id_type_type_);


  return result;
  }


result_t cli_neutron_publish_id_sample_sample (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_publish_id_sample_sample_;

  if(failed(result = cli_get_enum(&parser->tokens[1], sample_types, &neutron_publish_id_sample_sample_)))
    return result;

  result = neutron_publish_id_sample_sample_action(parser, neutron_publish_id_sample_sample_);


  return result;
  }


result_t cli_neutron_publish_id_publish_is_published (cli_t *parser)
  {
  result_t result;
  bool neutron_publish_id_publish_is_published_;

  if(failed(result = cli_get_bool(&parser->tokens[1], booleans, &neutron_publish_id_publish_is_published_)))
    return result;

  result = neutron_publish_id_publish_is_published_action(parser, neutron_publish_id_publish_is_published_);


  return result;
  }


result_t cli_neutron_publish_id_loopback_loopback (cli_t *parser)
  {
  result_t result;
  bool neutron_publish_id_loopback_loopback_;

  if(failed(result = cli_get_bool(&parser->tokens[1], booleans, &neutron_publish_id_loopback_loopback_)))
    return result;

  result = neutron_publish_id_loopback_loopback_action(parser, neutron_publish_id_loopback_loopback_);


  return result;
  }


result_t cli_neutron_publish_id_filter_filter_type_length_value (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_publish_id_filter_filter_type_length_value_;

  if(failed(result = cli_get_uint16(&parser->tokens[1], &neutron_publish_id_filter_filter_type_length_value_)))
    return result;

  result = neutron_publish_id_filter_filter_type_length_value_action(parser, neutron_publish_id_filter_filter_type_length_value_);


  return result;
  }


result_t cli_neutron_publish_id_filter_filter_type_coeff_index_value (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_publish_id_filter_filter_type_coeff_index_;
  float neutron_publish_id_filter_filter_type_coeff_index_value_;

  if(failed(result = cli_get_uint16(&parser->tokens[1], &neutron_publish_id_filter_filter_type_coeff_index_)))
    return result;

  if(failed(result = cli_get_float(&parser->tokens[2], &neutron_publish_id_filter_filter_type_coeff_index_value_)))
    return result;

  result = neutron_publish_id_filter_filter_type_coeff_index_value_action(parser, neutron_publish_id_filter_filter_type_coeff_index_, neutron_publish_id_filter_filter_type_coeff_index_value_);


  return result;
  }


result_t cli_neutron_publish_id_filter_filter_type_gain_value (cli_t *parser)
  {
  result_t result;
  float neutron_publish_id_filter_filter_type_gain_value_;

  if(failed(result = cli_get_float(&parser->tokens[1], &neutron_publish_id_filter_filter_type_gain_value_)))
    return result;

  result = neutron_publish_id_filter_filter_type_gain_value_action(parser, neutron_publish_id_filter_filter_type_gain_value_);


  return result;
  }


result_t cli_neutron_publish_id_filter_filter_type_exit (cli_t *parser)
  {
  result_t result;
  result = neutron_publish_id_filter_filter_type_exit_action(parser);


  return result;
  }


result_t cli_neutron_publish_id_filter_filter_type (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_publish_id_filter_filter_type_;

  if(failed(result = cli_get_enum(&parser->tokens[1], filter_types, &neutron_publish_id_filter_filter_type_)))
    return result;

  result = neutron_publish_id_filter_filter_type_action(parser, neutron_publish_id_filter_filter_type_);


  return result;
  }


result_t cli_neutron_publish_id_alarm_alarm_id_type_alarm_type (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_publish_id_alarm_alarm_id_type_alarm_type_;

  if(failed(result = cli_get_enum(&parser->tokens[1], alarm_types, &neutron_publish_id_alarm_alarm_id_type_alarm_type_)))
    return result;

  result = neutron_publish_id_alarm_alarm_id_type_alarm_type_action(parser, neutron_publish_id_alarm_alarm_id_type_alarm_type_);


  return result;
  }


result_t cli_neutron_publish_id_alarm_alarm_id_period_length (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_publish_id_alarm_alarm_id_period_length_;

  if(failed(result = cli_get_uint16(&parser->tokens[1], &neutron_publish_id_alarm_alarm_id_period_length_)))
    return result;

  result = neutron_publish_id_alarm_alarm_id_period_length_action(parser, neutron_publish_id_alarm_alarm_id_period_length_);


  return result;
  }


result_t cli_neutron_publish_id_alarm_alarm_id_max_max_value (cli_t *parser)
  {
  result_t result;
  float neutron_publish_id_alarm_alarm_id_max_max_value_;

  if(failed(result = cli_get_float(&parser->tokens[1], &neutron_publish_id_alarm_alarm_id_max_max_value_)))
    return result;

  result = neutron_publish_id_alarm_alarm_id_max_max_value_action(parser, neutron_publish_id_alarm_alarm_id_max_max_value_);


  return result;
  }


result_t cli_neutron_publish_id_alarm_alarm_id_min_min_value (cli_t *parser)
  {
  result_t result;
  float neutron_publish_id_alarm_alarm_id_min_min_value_;

  if(failed(result = cli_get_float(&parser->tokens[1], &neutron_publish_id_alarm_alarm_id_min_min_value_)))
    return result;

  result = neutron_publish_id_alarm_alarm_id_min_min_value_action(parser, neutron_publish_id_alarm_alarm_id_min_min_value_);


  return result;
  }


result_t cli_neutron_publish_id_alarm_alarm_id_reset_reset_id (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_publish_id_alarm_alarm_id_reset_reset_id_;

  if(failed(result = cli_get_enum(&parser->tokens[1], can_ids, &neutron_publish_id_alarm_alarm_id_reset_reset_id_)))
    return result;

  result = neutron_publish_id_alarm_alarm_id_reset_reset_id_action(parser, neutron_publish_id_alarm_alarm_id_reset_reset_id_);


  return result;
  }


result_t cli_neutron_publish_id_alarm_alarm_id_exit (cli_t *parser)
  {
  result_t result;
  result = neutron_publish_id_alarm_alarm_id_exit_action(parser);


  return result;
  }


result_t cli_neutron_publish_id_alarm_alarm_id (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_publish_id_alarm_alarm_id_;

  if(failed(result = cli_get_uint16(&parser->tokens[1], &neutron_publish_id_alarm_alarm_id_)))
    return result;

  result = neutron_publish_id_alarm_alarm_id_action(parser, neutron_publish_id_alarm_alarm_id_);


  return result;
  }


result_t cli_neutron_publish_id_exit (cli_t *parser)
  {
  result_t result;
  result = neutron_publish_id_exit_action(parser);


  return result;
  }


result_t cli_neutron_publish_id (cli_t *parser)
  {
  result_t result;
  uint16_t neutron_publish_id_;

  if(failed(result = cli_get_enum(&parser->tokens[1], can_ids, &neutron_publish_id_)))
    return result;

  result = neutron_publish_id_action(parser, neutron_publish_id_);


  return result;
  }


result_t cli_neutron_exit (cli_t *parser)
  {
  result_t result;
  result = neutron_exit_action(parser);


  return result;
  }


result_t cli_neutron (cli_t *parser)
  {
  result_t result;
  result = neutron_action(parser);


  return result;
  }


result_t cli_send_can_id_type_session_val1_val2_val3_val4 (cli_t *parser)
  {
  result_t result;
  uint16_t send_can_id_;
  uint16_t send_can_id_type_;
  uint16_t send_can_id_type_session_;
  string_t send_can_id_type_session_val1_ = 0;
  string_t send_can_id_type_session_val1_val2_ = 0;
  string_t send_can_id_type_session_val1_val2_val3_ = 0;
  string_t send_can_id_type_session_val1_val2_val3_val4_ = 0;

  if(failed(result = cli_get_enum(&parser->tokens[1], can_ids, &send_can_id_)))
    return result;

  if(failed(result = cli_get_enum(&parser->tokens[2], can_types, &send_can_id_type_)))
    return result;

  if(failed(result = cli_get_uint16(&parser->tokens[3], &send_can_id_type_session_)))
    return result;

  if(string_length(parser->tokens[4].buffer) > 0 &&
    failed(result = cli_get_string(&parser->tokens[4], &send_can_id_type_session_val1_)))
    return result;

  if(string_length(parser->tokens[5].buffer) > 0 &&
    failed(result = cli_get_string(&parser->tokens[5], &send_can_id_type_session_val1_val2_)))
    return result;

  if(string_length(parser->tokens[6].buffer) > 0 &&
    failed(result = cli_get_string(&parser->tokens[6], &send_can_id_type_session_val1_val2_val3_)))
    return result;

  if(string_length(parser->tokens[7].buffer) > 0 &&
    failed(result = cli_get_string(&parser->tokens[7], &send_can_id_type_session_val1_val2_val3_val4_)))
    return result;

  result = send_can_id_type_session_val1_val2_val3_val4_action(parser, send_can_id_, send_can_id_type_, send_can_id_type_session_, ((string_length(parser->tokens[4].buffer) > 0) ? send_can_id_type_session_val1_ : 0), ((string_length(parser->tokens[5].buffer) > 0) ? send_can_id_type_session_val1_val2_ : 0), ((string_length(parser->tokens[6].buffer) > 0) ? send_can_id_type_session_val1_val2_val3_ : 0), ((string_length(parser->tokens[7].buffer) > 0) ? send_can_id_type_session_val1_val2_val3_val4_ : 0));


  return result;
  }


result_t cli_exit (cli_t *parser)
  {
  result_t result;
  result = exit_action(parser);


  return result;
  }


result_t cli_ion_add_id_name_msg_handler (cli_t *parser)
  {
  result_t result;
  uint16_t ion_add_id_;
  string_t ion_add_id_name_ = 0;
  string_t ion_add_id_name_msg_handler_ = 0;

  if(failed(result = cli_get_enum(&parser->tokens[1], can_ids, &ion_add_id_)))
    return result;

  if(failed(result = cli_get_string(&parser->tokens[2], &ion_add_id_name_)))
    return result;

  if(failed(result = cli_get_string(&parser->tokens[3], &ion_add_id_name_msg_handler_)))
    return result;

  result = ion_add_id_name_msg_handler_action(parser, ion_add_id_, ion_add_id_name_, ion_add_id_name_msg_handler_);


  return result;
  }


result_t cli_ion_del_id_name (cli_t *parser)
  {
  result_t result;
  uint16_t ion_del_id_;
  string_t ion_del_id_name_ = 0;

  if(failed(result = cli_get_enum(&parser->tokens[1], can_ids, &ion_del_id_)))
    return result;

  if(failed(result = cli_get_string(&parser->tokens[2], &ion_del_id_name_)))
    return result;

  result = ion_del_id_name_action(parser, ion_del_id_, ion_del_id_name_);


  return result;
  }


result_t cli_ion_cat_name (cli_t *parser)
  {
  result_t result;
  string_t ion_cat_name_ = 0;

  if(failed(result = cli_get_string(&parser->tokens[1], &ion_cat_name_)))
    return result;

  result = ion_cat_name_action(parser, ion_cat_name_);


  return result;
  }


result_t cli_ion_edit_name (cli_t *parser)
  {
  result_t result;
  string_t ion_edit_name_ = 0;

  if(failed(result = cli_get_string(&parser->tokens[1], &ion_edit_name_)))
    return result;

  result = ion_edit_name_action(parser, ion_edit_name_);


  return result;
  }


result_t cli_ion_create_name_content (cli_t *parser)
  {
  result_t result;
  string_t ion_create_name_ = 0;
  string_t ion_create_name_content_ = 0;

  if(failed(result = cli_get_string(&parser->tokens[1], &ion_create_name_)))
    return result;

  if(string_length(parser->tokens[2].buffer) > 0 &&
    failed(result = cli_get_string(&parser->tokens[2], &ion_create_name_content_)))
    return result;

  result = ion_create_name_content_action(parser, ion_create_name_, ((string_length(parser->tokens[2].buffer) > 0) ? ion_create_name_content_ : 0));


  return result;
  }


result_t cli_ion_rm_name (cli_t *parser)
  {
  result_t result;
  string_t ion_rm_name_ = 0;

  if(failed(result = cli_get_string(&parser->tokens[1], &ion_rm_name_)))
    return result;

  result = ion_rm_name_action(parser, ion_rm_name_);


  return result;
  }


result_t cli_ion_ls_name (cli_t *parser)
  {
  result_t result;
  string_t ion_ls_name_ = 0;

  if(string_length(parser->tokens[1].buffer) > 0 &&
    failed(result = cli_get_string(&parser->tokens[1], &ion_ls_name_)))
    return result;

  result = ion_ls_name_action(parser, ((string_length(parser->tokens[1].buffer) > 0) ? ion_ls_name_ : 0));


  return result;
  }


result_t cli_ion_debug_name (cli_t *parser)
  {
  result_t result;
  string_t ion_debug_name_ = 0;

  if(string_length(parser->tokens[1].buffer) > 0 &&
    failed(result = cli_get_string(&parser->tokens[1], &ion_debug_name_)))
    return result;

  result = ion_debug_name_action(parser, ((string_length(parser->tokens[1].buffer) > 0) ? ion_debug_name_ : 0));


  return result;
  }


result_t cli_ion_exec_name (cli_t *parser)
  {
  result_t result;
  string_t ion_exec_name_ = 0;

  if(string_length(parser->tokens[1].buffer) > 0 &&
    failed(result = cli_get_string(&parser->tokens[1], &ion_exec_name_)))
    return result;

  result = ion_exec_name_action(parser, ((string_length(parser->tokens[1].buffer) > 0) ? ion_exec_name_ : 0));


  return result;
  }


result_t cli_ion_exit (cli_t *parser)
  {
  result_t result;
  result = ion_exit_action(parser);


  return result;
  }


result_t cli_ion (cli_t *parser)
  {
  result_t result;
  result = ion_action(parser);


  return result;
  }


static cli_node_t node_uint16_name_value_end;

static cli_node_t node_uint16_name_value;

static cli_node_t node_uint16_name;

static cli_node_t node_uint16;

static cli_node_t node_int16_name_value_end;

static cli_node_t node_int16_name_value;

static cli_node_t node_int16_name;

static cli_node_t node_int16;

static cli_node_t node_uint32_name_value_end;

static cli_node_t node_uint32_name_value;

static cli_node_t node_uint32_name;

static cli_node_t node_uint32;

static cli_node_t node_int32_name_value_end;

static cli_node_t node_int32_name_value;

static cli_node_t node_int32_name;

static cli_node_t node_int32;

static cli_node_t node_xyz_name_value_end;

static cli_node_t node_xyz_name_value;

static cli_node_t node_xyz_name;

static cli_node_t node_xyz;

static cli_node_t node_matrix_name_value_end;

static cli_node_t node_matrix_name_value;

static cli_node_t node_matrix_name;

static cli_node_t node_matrix;

static cli_node_t node_string_name_value_end;

static cli_node_t node_string_name_value;

static cli_node_t node_string_name;

static cli_node_t node_string;

static cli_node_t node_bool_name_value_end;

static cli_node_t node_bool_name_value;

static cli_node_t node_bool_name;

static cli_node_t node_bool;

static cli_node_t node_float_name_value_end;

static cli_node_t node_float_name_value;

static cli_node_t node_float_name;

static cli_node_t node_float;

static cli_node_t node_edit_name_end;

static cli_node_t node_edit_name;

static cli_node_t node_edit;

static cli_node_t node_cat_name_end;

static cli_node_t node_cat_name;

static cli_node_t node_cat;

static cli_node_t node_rm_name_end;

static cli_node_t node_rm_name;

static cli_node_t node_rm;

static cli_node_t node_mkdir_path_end;

static cli_node_t node_mkdir_path;

static cli_node_t node_mkdir;

static cli_node_t node_rmdir_path_end;

static cli_node_t node_rmdir_path;

static cli_node_t node_rmdir;

static cli_node_t node_cd_path_end;

static cli_node_t node_cd_path;

static cli_node_t node_cd;

static cli_node_t node_ls_path_recursive_end;

static cli_node_t node_ls_path_recursive;

static cli_node_t node_ls_path;

static cli_node_t node_ls;

static cli_node_t node_neutron_ls_id_end;

static cli_node_t node_neutron_ls_id;

static cli_node_t node_neutron_ls;

static cli_node_t node_neutron_rm_id_end;

static cli_node_t node_neutron_rm_id;

static cli_node_t node_neutron_rm;

static cli_node_t node_neutron_publish_id_rate_rate_end;

static cli_node_t node_neutron_publish_id_rate_rate;

static cli_node_t node_neutron_publish_id_rate;

static cli_node_t node_neutron_publish_id_type_type_end;

static cli_node_t node_neutron_publish_id_type_type;

static cli_node_t node_neutron_publish_id_type;

static cli_node_t node_neutron_publish_id_sample_sample_end;

static cli_node_t node_neutron_publish_id_sample_sample;

static cli_node_t node_neutron_publish_id_sample;

static cli_node_t node_neutron_publish_id_publish_is_published_end;

static cli_node_t node_neutron_publish_id_publish_is_published;

static cli_node_t node_neutron_publish_id_publish;

static cli_node_t node_neutron_publish_id_loopback_loopback_end;

static cli_node_t node_neutron_publish_id_loopback_loopback;

static cli_node_t node_neutron_publish_id_loopback;

static cli_node_t node_neutron_publish_id_filter_filter_type_length_value_end;

static cli_node_t node_neutron_publish_id_filter_filter_type_length_value;

static cli_node_t node_neutron_publish_id_filter_filter_type_length;

static cli_node_t node_neutron_publish_id_filter_filter_type_coeff_index_value_end;

static cli_node_t node_neutron_publish_id_filter_filter_type_coeff_index_value;

static cli_node_t node_neutron_publish_id_filter_filter_type_coeff_index;

static cli_node_t node_neutron_publish_id_filter_filter_type_coeff;

static cli_node_t node_neutron_publish_id_filter_filter_type_gain_value_end;

static cli_node_t node_neutron_publish_id_filter_filter_type_gain_value;

static cli_node_t node_neutron_publish_id_filter_filter_type_gain;

static cli_node_t node_neutron_publish_id_filter_filter_type_exit_end;

static cli_node_t node_neutron_publish_id_filter_filter_type_exit;

static cli_node_t node_neutron_publish_id_filter_filter_type_end;

static cli_node_t node_neutron_publish_id_filter_filter_type;

static cli_node_t node_neutron_publish_id_filter;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_type_alarm_type_end;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_type_alarm_type;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_type;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_period_length_end;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_period_length;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_period;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_max_max_value_end;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_max_max_value;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_max;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_min_min_value_end;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_min_min_value;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_min;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_reset_reset_id_end;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_reset_reset_id;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_reset;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_exit_end;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_exit;

static cli_node_t node_neutron_publish_id_alarm_alarm_id_end;

static cli_node_t node_neutron_publish_id_alarm_alarm_id;

static cli_node_t node_neutron_publish_id_alarm;

static cli_node_t node_neutron_publish_id_exit_end;

static cli_node_t node_neutron_publish_id_exit;

static cli_node_t node_neutron_publish_id_end;

static cli_node_t node_neutron_publish_id;

static cli_node_t node_neutron_publish;

static cli_node_t node_neutron_exit_end;

static cli_node_t node_neutron_exit;

static cli_node_t node_neutron_end;

static cli_node_t node_neutron;

static cli_node_t node_send_can_id_type_session_val1_val2_val3_val4_end;

static cli_node_t node_send_can_id_type_session_val1_val2_val3_val4;

static cli_node_t node_send_can_id_type_session_val1_val2_val3;

static cli_node_t node_send_can_id_type_session_val1_val2;

static cli_node_t node_send_can_id_type_session_val1;

static cli_node_t node_send_can_id_type_session;

static cli_node_t node_send_can_id_type;

static cli_node_t node_send_can_id;

static cli_node_t node_send_can;

static cli_node_t node_exit_end;

static cli_node_t node_exit;

static cli_node_t node_ion_add_id_name_msg_handler_end;

static cli_node_t node_ion_add_id_name_msg_handler;

static cli_node_t node_ion_add_id_name;

static cli_node_t node_ion_add_id;

static cli_node_t node_ion_add;

static cli_node_t node_ion_del_id_name_end;

static cli_node_t node_ion_del_id_name;

static cli_node_t node_ion_del_id;

static cli_node_t node_ion_del;

static cli_node_t node_ion_cat_name_end;

static cli_node_t node_ion_cat_name;

static cli_node_t node_ion_cat;

static cli_node_t node_ion_edit_name_end;

static cli_node_t node_ion_edit_name;

static cli_node_t node_ion_edit;

static cli_node_t node_ion_create_name_content_end;

static cli_node_t node_ion_create_name_content;

static cli_node_t node_ion_create_name;

static cli_node_t node_ion_create;

static cli_node_t node_ion_rm_name_end;

static cli_node_t node_ion_rm_name;

static cli_node_t node_ion_rm;

static cli_node_t node_ion_ls_name_end;

static cli_node_t node_ion_ls_name;

static cli_node_t node_ion_ls;

static cli_node_t node_ion_debug_name_end;

static cli_node_t node_ion_debug_name;

static cli_node_t node_ion_debug;

static cli_node_t node_ion_exec_name_end;

static cli_node_t node_ion_exec_name;

static cli_node_t node_ion_exec;

static cli_node_t node_ion_exit_end;

static cli_node_t node_ion_exit;

static cli_node_t node_ion_end;

static cli_node_t node_ion;

static cli_node_t node_uint16_name_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_uint16_name_value,
  0,
  0,
  0
  };


static cli_node_t node_uint16_name_value = {
  CLI_NODE_UINT16,
  0,
  "UINT16:value",
  0,
  0,
  &node_uint16_name_value_end
  };


static cli_node_t node_uint16_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_uint16_name_value
  };


static cli_node_t node_uint16 = {
  CLI_NODE_KEYWORD,
  0,
  "uint16",
  0,
  &node_int16,
  &node_uint16_name
  };


static cli_node_t node_int16_name_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_int16_name_value,
  0,
  0,
  0
  };


static cli_node_t node_int16_name_value = {
  CLI_NODE_INT16,
  0,
  "INT16:value",
  0,
  0,
  &node_int16_name_value_end
  };


static cli_node_t node_int16_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_int16_name_value
  };


static cli_node_t node_int16 = {
  CLI_NODE_KEYWORD,
  0,
  "int16",
  0,
  &node_uint32,
  &node_int16_name
  };


static cli_node_t node_uint32_name_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_uint32_name_value,
  0,
  0,
  0
  };


static cli_node_t node_uint32_name_value = {
  CLI_NODE_UINT32,
  0,
  "UINT32:value",
  0,
  0,
  &node_uint32_name_value_end
  };


static cli_node_t node_uint32_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_uint32_name_value
  };


static cli_node_t node_uint32 = {
  CLI_NODE_KEYWORD,
  0,
  "uint32",
  0,
  &node_int32,
  &node_uint32_name
  };


static cli_node_t node_int32_name_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_int32_name_value,
  0,
  0,
  0
  };


static cli_node_t node_int32_name_value = {
  CLI_NODE_INT32,
  0,
  "INT32:value",
  0,
  0,
  &node_int32_name_value_end
  };


static cli_node_t node_int32_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_int32_name_value
  };


static cli_node_t node_int32 = {
  CLI_NODE_KEYWORD,
  0,
  "int32",
  0,
  &node_xyz,
  &node_int32_name
  };


static cli_node_t node_xyz_name_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_xyz_name_value,
  0,
  0,
  0
  };


static cli_node_t node_xyz_name_value = {
  CLI_NODE_XYZ,
  0,
  "XYZ:value",
  0,
  0,
  &node_xyz_name_value_end
  };


static cli_node_t node_xyz_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_xyz_name_value
  };


static cli_node_t node_xyz = {
  CLI_NODE_KEYWORD,
  0,
  "xyz",
  0,
  &node_matrix,
  &node_xyz_name
  };


static cli_node_t node_matrix_name_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_matrix_name_value,
  0,
  0,
  0
  };


static cli_node_t node_matrix_name_value = {
  CLI_NODE_MATRIX,
  0,
  "MATRIX:value",
  0,
  0,
  &node_matrix_name_value_end
  };


static cli_node_t node_matrix_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_matrix_name_value
  };


static cli_node_t node_matrix = {
  CLI_NODE_KEYWORD,
  0,
  "matrix",
  0,
  &node_string,
  &node_matrix_name
  };


static cli_node_t node_string_name_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_string_name_value,
  0,
  0,
  0
  };


static cli_node_t node_string_name_value = {
  CLI_NODE_STRING,
  0,
  "STRING:value",
  0,
  0,
  &node_string_name_value_end
  };


static cli_node_t node_string_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_string_name_value
  };


static cli_node_t node_string = {
  CLI_NODE_KEYWORD,
  0,
  "string",
  0,
  &node_bool,
  &node_string_name
  };


static cli_node_t node_bool_name_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_bool_name_value,
  0,
  0,
  0
  };


static cli_node_t node_bool_name_value = {
  CLI_NODE_ENUM,
  0,
  &booleans,
  0,
  0,
  &node_bool_name_value_end
  };


static cli_node_t node_bool_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_bool_name_value
  };


static cli_node_t node_bool = {
  CLI_NODE_KEYWORD,
  0,
  "bool",
  0,
  &node_float,
  &node_bool_name
  };


static cli_node_t node_float_name_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_float_name_value,
  0,
  0,
  0
  };


static cli_node_t node_float_name_value = {
  CLI_NODE_FLOAT,
  0,
  "FLOAT:value",
  0,
  0,
  &node_float_name_value_end
  };


static cli_node_t node_float_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_float_name_value
  };


static cli_node_t node_float = {
  CLI_NODE_KEYWORD,
  0,
  "float",
  0,
  &node_edit,
  &node_float_name
  };


static cli_node_t node_edit_name_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_edit_name,
  0,
  0,
  0
  };


static cli_node_t node_edit_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_edit_name_end
  };


static cli_node_t node_edit = {
  CLI_NODE_KEYWORD,
  0,
  "edit",
  0,
  &node_cat,
  &node_edit_name
  };


static cli_node_t node_cat_name_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_cat_name,
  0,
  0,
  0
  };


static cli_node_t node_cat_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_cat_name_end
  };


static cli_node_t node_cat = {
  CLI_NODE_KEYWORD,
  0,
  "cat",
  0,
  &node_rm,
  &node_cat_name
  };


static cli_node_t node_rm_name_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_rm_name,
  0,
  0,
  0
  };


static cli_node_t node_rm_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_rm_name_end
  };


static cli_node_t node_rm = {
  CLI_NODE_KEYWORD,
  0,
  "rm",
  0,
  &node_mkdir,
  &node_rm_name
  };


static cli_node_t node_mkdir_path_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_mkdir_path,
  0,
  0,
  0
  };


static cli_node_t node_mkdir_path = {
  CLI_NODE_STRING,
  0,
  "STRING:path",
  0,
  0,
  &node_mkdir_path_end
  };


static cli_node_t node_mkdir = {
  CLI_NODE_KEYWORD,
  0,
  "mkdir",
  0,
  &node_rmdir,
  &node_mkdir_path
  };


static cli_node_t node_rmdir_path_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_rmdir_path,
  0,
  0,
  0
  };


static cli_node_t node_rmdir_path = {
  CLI_NODE_STRING,
  0,
  "STRING:path",
  0,
  0,
  &node_rmdir_path_end
  };


static cli_node_t node_rmdir = {
  CLI_NODE_KEYWORD,
  0,
  "rmdir",
  0,
  &node_cd,
  &node_rmdir_path
  };


static cli_node_t node_cd_path_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_cd_path,
  0,
  0,
  0
  };


static cli_node_t node_cd_path = {
  CLI_NODE_STRING,
  0,
  "STRING:path",
  0,
  0,
  &node_cd_path_end
  };


static cli_node_t node_cd = {
  CLI_NODE_KEYWORD,
  0,
  "cd",
  0,
  &node_ls,
  &node_cd_path
  };


static cli_node_t node_ls_path_recursive_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_ls_path_recursive,
  0,
  0,
  0
  };


static cli_node_t node_ls_path_recursive = {
  CLI_NODE_KEYWORD,
  CLI_NODE_FLAGS_OPT_START | CLI_NODE_FLAGS_OPT_END | CLI_NODE_FLAGS_OPT_PARTIAL,
  "recursive",
  0,
  0,
  &node_ls_path_recursive_end
  };


static cli_node_t node_ls_path = {
  CLI_NODE_STRING,
  0,
  "STRING:path",
  0,
  0,
  &node_ls_path_recursive
  };


static cli_node_t node_ls = {
  CLI_NODE_KEYWORD,
  0,
  "ls",
  0,
  &node_neutron,
  &node_ls_path
  };


static cli_node_t node_neutron_ls_id_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_ls_id,
  0,
  0,
  0
  };


static cli_node_t node_neutron_ls_id = {
  CLI_NODE_ENUM,
  CLI_NODE_FLAGS_OPT_START | CLI_NODE_FLAGS_OPT_END | CLI_NODE_FLAGS_OPT_PARTIAL,
  &can_ids,
  0,
  0,
  &node_neutron_ls_id_end
  };


static cli_node_t node_neutron_ls = {
  CLI_NODE_KEYWORD,
  0,
  "ls",
  0,
  &node_neutron_rm,
  &node_neutron_ls_id
  };


static cli_node_t node_neutron_rm_id_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_rm_id,
  0,
  0,
  0
  };


static cli_node_t node_neutron_rm_id = {
  CLI_NODE_ENUM,
  0,
  &can_ids,
  0,
  0,
  &node_neutron_rm_id_end
  };


static cli_node_t node_neutron_rm = {
  CLI_NODE_KEYWORD,
  0,
  "rm",
  0,
  &node_neutron_publish,
  &node_neutron_rm_id
  };


static cli_node_t node_neutron_publish_id_rate_rate_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_rate_rate,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_rate_rate = {
  CLI_NODE_UINT16,
  0,
  "UINT16:rate",
  0,
  0,
  &node_neutron_publish_id_rate_rate_end
  };


static cli_node_t node_neutron_publish_id_rate = {
  CLI_NODE_KEYWORD,
  0,
  "rate",
  0,
  &node_neutron_publish_id_type,
  &node_neutron_publish_id_rate_rate
  };


static cli_node_t node_neutron_publish_id_type_type_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_type_type,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_type_type = {
  CLI_NODE_ENUM,
  0,
  &publish_types,
  0,
  0,
  &node_neutron_publish_id_type_type_end
  };


static cli_node_t node_neutron_publish_id_type = {
  CLI_NODE_KEYWORD,
  0,
  "type",
  0,
  &node_neutron_publish_id_sample,
  &node_neutron_publish_id_type_type
  };


static cli_node_t node_neutron_publish_id_sample_sample_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_sample_sample,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_sample_sample = {
  CLI_NODE_ENUM,
  0,
  &sample_types,
  0,
  0,
  &node_neutron_publish_id_sample_sample_end
  };


static cli_node_t node_neutron_publish_id_sample = {
  CLI_NODE_KEYWORD,
  0,
  "sample",
  0,
  &node_neutron_publish_id_publish,
  &node_neutron_publish_id_sample_sample
  };


static cli_node_t node_neutron_publish_id_publish_is_published_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_publish_is_published,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_publish_is_published = {
  CLI_NODE_ENUM,
  0,
  &booleans,
  0,
  0,
  &node_neutron_publish_id_publish_is_published_end
  };


static cli_node_t node_neutron_publish_id_publish = {
  CLI_NODE_KEYWORD,
  0,
  "publish",
  0,
  &node_neutron_publish_id_loopback,
  &node_neutron_publish_id_publish_is_published
  };


static cli_node_t node_neutron_publish_id_loopback_loopback_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_loopback_loopback,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_loopback_loopback = {
  CLI_NODE_ENUM,
  0,
  &booleans,
  0,
  0,
  &node_neutron_publish_id_loopback_loopback_end
  };


static cli_node_t node_neutron_publish_id_loopback = {
  CLI_NODE_KEYWORD,
  0,
  "loopback",
  0,
  &node_neutron_publish_id_filter,
  &node_neutron_publish_id_loopback_loopback
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_length_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_filter_filter_type_length_value,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_length_value = {
  CLI_NODE_UINT16,
  0,
  "UINT16:value",
  0,
  0,
  &node_neutron_publish_id_filter_filter_type_length_value_end
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_length = {
  CLI_NODE_KEYWORD,
  0,
  "length",
  0,
  &node_neutron_publish_id_filter_filter_type_coeff,
  &node_neutron_publish_id_filter_filter_type_length_value
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_coeff_index_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_filter_filter_type_coeff_index_value,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_coeff_index_value = {
  CLI_NODE_FLOAT,
  0,
  "FLOAT:value",
  0,
  0,
  &node_neutron_publish_id_filter_filter_type_coeff_index_value_end
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_coeff_index = {
  CLI_NODE_UINT16,
  0,
  "UINT16:index",
  0,
  0,
  &node_neutron_publish_id_filter_filter_type_coeff_index_value
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_coeff = {
  CLI_NODE_KEYWORD,
  0,
  "coeff",
  0,
  &node_neutron_publish_id_filter_filter_type_gain,
  &node_neutron_publish_id_filter_filter_type_coeff_index
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_gain_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_filter_filter_type_gain_value,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_gain_value = {
  CLI_NODE_FLOAT,
  0,
  "FLOAT:value",
  0,
  0,
  &node_neutron_publish_id_filter_filter_type_gain_value_end
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_gain = {
  CLI_NODE_KEYWORD,
  0,
  "gain",
  0,
  &node_neutron_publish_id_filter_filter_type_exit,
  &node_neutron_publish_id_filter_filter_type_gain_value
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_exit_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_filter_filter_type_exit,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_exit = {
  CLI_NODE_KEYWORD,
  0,
  "exit",
  0,
  0,
  &node_neutron_publish_id_filter_filter_type_exit_end
  };


static cli_node_t node_neutron_publish_id_filter_filter_type_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_filter_filter_type,
  0,
  0,
  &node_neutron_publish_id_filter_filter_type_length
  };


static cli_node_t node_neutron_publish_id_filter_filter_type = {
  CLI_NODE_ENUM,
  0,
  &filter_types,
  0,
  0,
  &node_neutron_publish_id_filter_filter_type_end
  };


static cli_node_t node_neutron_publish_id_filter = {
  CLI_NODE_KEYWORD,
  0,
  "filter",
  0,
  &node_neutron_publish_id_alarm,
  &node_neutron_publish_id_filter_filter_type
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_type_alarm_type_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_alarm_alarm_id_type_alarm_type,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_type_alarm_type = {
  CLI_NODE_ENUM,
  0,
  &alarm_types,
  0,
  0,
  &node_neutron_publish_id_alarm_alarm_id_type_alarm_type_end
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_type = {
  CLI_NODE_KEYWORD,
  0,
  "type",
  0,
  &node_neutron_publish_id_alarm_alarm_id_period,
  &node_neutron_publish_id_alarm_alarm_id_type_alarm_type
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_period_length_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_alarm_alarm_id_period_length,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_period_length = {
  CLI_NODE_UINT16,
  0,
  "UINT16:length",
  0,
  0,
  &node_neutron_publish_id_alarm_alarm_id_period_length_end
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_period = {
  CLI_NODE_KEYWORD,
  0,
  "period",
  0,
  &node_neutron_publish_id_alarm_alarm_id_max,
  &node_neutron_publish_id_alarm_alarm_id_period_length
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_max_max_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_alarm_alarm_id_max_max_value,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_max_max_value = {
  CLI_NODE_FLOAT,
  0,
  "FLOAT:max_value",
  0,
  0,
  &node_neutron_publish_id_alarm_alarm_id_max_max_value_end
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_max = {
  CLI_NODE_KEYWORD,
  0,
  "max",
  0,
  &node_neutron_publish_id_alarm_alarm_id_min,
  &node_neutron_publish_id_alarm_alarm_id_max_max_value
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_min_min_value_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_alarm_alarm_id_min_min_value,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_min_min_value = {
  CLI_NODE_FLOAT,
  0,
  "FLOAT:min_value",
  0,
  0,
  &node_neutron_publish_id_alarm_alarm_id_min_min_value_end
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_min = {
  CLI_NODE_KEYWORD,
  0,
  "min",
  0,
  &node_neutron_publish_id_alarm_alarm_id_reset,
  &node_neutron_publish_id_alarm_alarm_id_min_min_value
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_reset_reset_id_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_alarm_alarm_id_reset_reset_id,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_reset_reset_id = {
  CLI_NODE_ENUM,
  0,
  &can_ids,
  0,
  0,
  &node_neutron_publish_id_alarm_alarm_id_reset_reset_id_end
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_reset = {
  CLI_NODE_KEYWORD,
  0,
  "reset",
  0,
  &node_neutron_publish_id_alarm_alarm_id_exit,
  &node_neutron_publish_id_alarm_alarm_id_reset_reset_id
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_exit_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_alarm_alarm_id_exit,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_exit = {
  CLI_NODE_KEYWORD,
  0,
  "exit",
  0,
  0,
  &node_neutron_publish_id_alarm_alarm_id_exit_end
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_alarm_alarm_id,
  0,
  0,
  &node_neutron_publish_id_alarm_alarm_id_type
  };


static cli_node_t node_neutron_publish_id_alarm_alarm_id = {
  CLI_NODE_UINT16,
  0,
  "UINT16:alarm_id",
  0,
  0,
  &node_neutron_publish_id_alarm_alarm_id_end
  };


static cli_node_t node_neutron_publish_id_alarm = {
  CLI_NODE_KEYWORD,
  0,
  "alarm",
  0,
  &node_neutron_publish_id_exit,
  &node_neutron_publish_id_alarm_alarm_id
  };


static cli_node_t node_neutron_publish_id_exit_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id_exit,
  0,
  0,
  0
  };


static cli_node_t node_neutron_publish_id_exit = {
  CLI_NODE_KEYWORD,
  0,
  "exit",
  0,
  0,
  &node_neutron_publish_id_exit_end
  };


static cli_node_t node_neutron_publish_id_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_publish_id,
  0,
  0,
  &node_neutron_publish_id_rate
  };


static cli_node_t node_neutron_publish_id = {
  CLI_NODE_ENUM,
  0,
  &can_ids,
  0,
  0,
  &node_neutron_publish_id_end
  };


static cli_node_t node_neutron_publish = {
  CLI_NODE_KEYWORD,
  0,
  "publish",
  0,
  &node_neutron_exit,
  &node_neutron_publish_id
  };


static cli_node_t node_neutron_exit_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron_exit,
  0,
  0,
  0
  };


static cli_node_t node_neutron_exit = {
  CLI_NODE_KEYWORD,
  0,
  "exit",
  0,
  0,
  &node_neutron_exit_end
  };


static cli_node_t node_neutron_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_neutron,
  0,
  0,
  &node_neutron_ls
  };


static cli_node_t node_neutron = {
  CLI_NODE_KEYWORD,
  0,
  "neutron",
  0,
  &node_send_can,
  &node_neutron_end
  };


static cli_node_t node_send_can_id_type_session_val1_val2_val3_val4_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_send_can_id_type_session_val1_val2_val3_val4,
  0,
  0,
  0
  };


static cli_node_t node_send_can_id_type_session_val1_val2_val3_val4 = {
  CLI_NODE_STRING,
  CLI_NODE_FLAGS_OPT_START | CLI_NODE_FLAGS_OPT_END | CLI_NODE_FLAGS_OPT_PARTIAL,
  "STRING:val4",
  0,
  0,
  &node_send_can_id_type_session_val1_val2_val3_val4_end
  };


static cli_node_t node_send_can_id_type_session_val1_val2_val3 = {
  CLI_NODE_STRING,
  CLI_NODE_FLAGS_OPT_START | CLI_NODE_FLAGS_OPT_PARTIAL,
  "STRING:val3",
  0,
  0,
  &node_send_can_id_type_session_val1_val2_val3_val4
  };


static cli_node_t node_send_can_id_type_session_val1_val2 = {
  CLI_NODE_STRING,
  CLI_NODE_FLAGS_OPT_START | CLI_NODE_FLAGS_OPT_PARTIAL,
  "STRING:val2",
  0,
  0,
  &node_send_can_id_type_session_val1_val2_val3
  };


static cli_node_t node_send_can_id_type_session_val1 = {
  CLI_NODE_STRING,
  CLI_NODE_FLAGS_OPT_START | CLI_NODE_FLAGS_OPT_PARTIAL,
  "STRING:val1",
  0,
  0,
  &node_send_can_id_type_session_val1_val2
  };


static cli_node_t node_send_can_id_type_session = {
  CLI_NODE_UINT16,
  0,
  "UINT16:session",
  0,
  0,
  &node_send_can_id_type_session_val1
  };


static cli_node_t node_send_can_id_type = {
  CLI_NODE_ENUM,
  0,
  &can_types,
  0,
  0,
  &node_send_can_id_type_session
  };


static cli_node_t node_send_can_id = {
  CLI_NODE_ENUM,
  0,
  &can_ids,
  0,
  0,
  &node_send_can_id_type
  };


static cli_node_t node_send_can = {
  CLI_NODE_KEYWORD,
  0,
  "send_can",
  0,
  &node_exit,
  &node_send_can_id
  };


static cli_node_t node_exit_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_exit,
  0,
  0,
  0
  };


static cli_node_t node_exit = {
  CLI_NODE_KEYWORD,
  0,
  "exit",
  0,
  &node_ion,
  &node_exit_end
  };


static cli_node_t node_ion_add_id_name_msg_handler_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_ion_add_id_name_msg_handler,
  0,
  0,
  0
  };


static cli_node_t node_ion_add_id_name_msg_handler = {
  CLI_NODE_STRING,
  0,
  "STRING:msg_handler",
  0,
  0,
  &node_ion_add_id_name_msg_handler_end
  };


static cli_node_t node_ion_add_id_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_ion_add_id_name_msg_handler
  };


static cli_node_t node_ion_add_id = {
  CLI_NODE_ENUM,
  0,
  &can_ids,
  0,
  0,
  &node_ion_add_id_name
  };


static cli_node_t node_ion_add = {
  CLI_NODE_KEYWORD,
  0,
  "add",
  0,
  &node_ion_del,
  &node_ion_add_id
  };


static cli_node_t node_ion_del_id_name_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_ion_del_id_name,
  0,
  0,
  0
  };


static cli_node_t node_ion_del_id_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_ion_del_id_name_end
  };


static cli_node_t node_ion_del_id = {
  CLI_NODE_ENUM,
  0,
  &can_ids,
  0,
  0,
  &node_ion_del_id_name
  };


static cli_node_t node_ion_del = {
  CLI_NODE_KEYWORD,
  0,
  "del",
  0,
  &node_ion_cat,
  &node_ion_del_id
  };


static cli_node_t node_ion_cat_name_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_ion_cat_name,
  0,
  0,
  0
  };


static cli_node_t node_ion_cat_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_ion_cat_name_end
  };


static cli_node_t node_ion_cat = {
  CLI_NODE_KEYWORD,
  0,
  "cat",
  0,
  &node_ion_edit,
  &node_ion_cat_name
  };


static cli_node_t node_ion_edit_name_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_ion_edit_name,
  0,
  0,
  0
  };


static cli_node_t node_ion_edit_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_ion_edit_name_end
  };


static cli_node_t node_ion_edit = {
  CLI_NODE_KEYWORD,
  0,
  "edit",
  0,
  &node_ion_create,
  &node_ion_edit_name
  };


static cli_node_t node_ion_create_name_content_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_ion_create_name_content,
  0,
  0,
  0
  };


static cli_node_t node_ion_create_name_content = {
  CLI_NODE_STRING,
  CLI_NODE_FLAGS_OPT_START | CLI_NODE_FLAGS_OPT_END | CLI_NODE_FLAGS_OPT_PARTIAL,
  "STRING:content",
  0,
  0,
  &node_ion_create_name_content_end
  };


static cli_node_t node_ion_create_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_ion_create_name_content
  };


static cli_node_t node_ion_create = {
  CLI_NODE_KEYWORD,
  0,
  "create",
  0,
  &node_ion_rm,
  &node_ion_create_name
  };


static cli_node_t node_ion_rm_name_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_ion_rm_name,
  0,
  0,
  0
  };


static cli_node_t node_ion_rm_name = {
  CLI_NODE_STRING,
  0,
  "STRING:name",
  0,
  0,
  &node_ion_rm_name_end
  };


static cli_node_t node_ion_rm = {
  CLI_NODE_KEYWORD,
  0,
  "rm",
  0,
  &node_ion_ls,
  &node_ion_rm_name
  };


static cli_node_t node_ion_ls_name_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_ion_ls_name,
  0,
  0,
  0
  };


static cli_node_t node_ion_ls_name = {
  CLI_NODE_STRING,
  CLI_NODE_FLAGS_OPT_START | CLI_NODE_FLAGS_OPT_END | CLI_NODE_FLAGS_OPT_PARTIAL,
  "STRING:name",
  0,
  0,
  &node_ion_ls_name_end
  };


static cli_node_t node_ion_ls = {
  CLI_NODE_KEYWORD,
  0,
  "ls",
  0,
  &node_ion_debug,
  &node_ion_ls_name
  };


static cli_node_t node_ion_debug_name_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_ion_debug_name,
  0,
  0,
  0
  };


static cli_node_t node_ion_debug_name = {
  CLI_NODE_STRING,
  CLI_NODE_FLAGS_OPT_START | CLI_NODE_FLAGS_OPT_END | CLI_NODE_FLAGS_OPT_PARTIAL,
  "STRING:name",
  0,
  0,
  &node_ion_debug_name_end
  };


static cli_node_t node_ion_debug = {
  CLI_NODE_KEYWORD,
  0,
  "debug",
  0,
  &node_ion_exec,
  &node_ion_debug_name
  };


static cli_node_t node_ion_exec_name_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_ion_exec_name,
  0,
  0,
  0
  };


static cli_node_t node_ion_exec_name = {
  CLI_NODE_STRING,
  CLI_NODE_FLAGS_OPT_START | CLI_NODE_FLAGS_OPT_END | CLI_NODE_FLAGS_OPT_PARTIAL,
  "STRING:name",
  0,
  0,
  &node_ion_exec_name_end
  };


static cli_node_t node_ion_exec = {
  CLI_NODE_KEYWORD,
  0,
  "exec",
  0,
  &node_ion_exit,
  &node_ion_exec_name
  };


static cli_node_t node_ion_exit_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_ion_exit,
  0,
  0,
  0
  };


static cli_node_t node_ion_exit = {
  CLI_NODE_KEYWORD,
  0,
  "exit",
  0,
  0,
  &node_ion_exit_end
  };


static cli_node_t node_ion_end = {
  CLI_NODE_END,
  CLI_NODE_FLAGS_OPT_END,
  cli_ion,
  0,
  0,
  &node_ion_add
  };


static cli_node_t node_ion = {
  CLI_NODE_KEYWORD,
  0,
  "ion",
  0,
  0,
  &node_ion_end
  };


cli_node_t ion_cli_root = {
  CLI_NODE_ROOT,
  0,
  0,
  "Root node of the parser tree",
  0,
  &node_uint16
  };


