//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "CanFly_CoreLibrary.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_CanFly_CoreLibrary_CanFly_Syscall::RegCreateKey___STATIC__U4__U4__STRING,
    Library_CanFly_CoreLibrary_CanFly_Syscall::RegOpenKey___STATIC__U4__U4__STRING,
    Library_CanFly_CoreLibrary_CanFly_Syscall::RegGetInt8___STATIC__I1__U4__STRING,
    Library_CanFly_CoreLibrary_CanFly_Syscall::RegSetInt8___STATIC__VOID__U4__STRING__I1,
    Library_CanFly_CoreLibrary_CanFly_Syscall::RegGetUint8___STATIC__U1__U4__STRING,
    Library_CanFly_CoreLibrary_CanFly_Syscall::RegSetUint8___STATIC__VOID__U4__STRING__U1,
    Library_CanFly_CoreLibrary_CanFly_Syscall::RegGetInt16___STATIC__I2__U4__STRING,
    Library_CanFly_CoreLibrary_CanFly_Syscall::RegSetInt16___STATIC__VOID__U4__STRING__I2,
    Library_CanFly_CoreLibrary_CanFly_Syscall::RegGetUint16___STATIC__U2__U4__STRING,
    Library_CanFly_CoreLibrary_CanFly_Syscall::RegSetUint16___STATIC__VOID__U4__STRING__U2,
    Library_CanFly_CoreLibrary_CanFly_Syscall::RegGetInt32___STATIC__I4__U4__STRING,
    Library_CanFly_CoreLibrary_CanFly_Syscall::RegSetInt32___STATIC__VOID__U4__STRING__I4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::RegGetUint32___STATIC__U4__U4__STRING,
    Library_CanFly_CoreLibrary_CanFly_Syscall::RegSetUint32___STATIC__VOID__U4__STRING__U4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::RegGetString___STATIC__STRING__U4__STRING,
    Library_CanFly_CoreLibrary_CanFly_Syscall::RegSetString___STATIC__VOID__U4__STRING__STRING,
    Library_CanFly_CoreLibrary_CanFly_Syscall::RegGetFloat___STATIC__R4__U4__STRING,
    Library_CanFly_CoreLibrary_CanFly_Syscall::RegSetFloat___STATIC__VOID__U4__STRING__R4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::RegGetBool___STATIC__BOOLEAN__U4__STRING,
    Library_CanFly_CoreLibrary_CanFly_Syscall::RegSetBool___STATIC__VOID__U4__STRING__BOOLEAN,
    Library_CanFly_CoreLibrary_CanFly_Syscall::RegEnumKey___STATIC__STRING__U4__BYREF_U4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::OpenScreen___STATIC__U4__U2__U2,
    Library_CanFly_CoreLibrary_CanFly_Syscall::CreateWindow___STATIC__U4__U4__I4__I4__I4__I4__U2,
    Library_CanFly_CoreLibrary_CanFly_Syscall::CreateChildWindow___STATIC__U4__U4__I4__I4__I4__I4__U2,
    Library_CanFly_CoreLibrary_CanFly_Syscall::CloseWindow___STATIC__VOID__U4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::SendMessage___STATIC__VOID__U4__U2__U2__U1__U1__U1__U1__U1__U1__U1__U1,
    Library_CanFly_CoreLibrary_CanFly_Syscall::PostMessage___STATIC__VOID__U4__U2__U2__U1__U1__U1__U1__U1__U1__U1__U1,
    Library_CanFly_CoreLibrary_CanFly_Syscall::GetWindowRect___STATIC__VOID__U4__BYREF_I4__BYREF_I4__BYREF_I4__BYREF_I4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::GetWindowPos___STATIC__VOID__U4__BYREF_I4__BYREF_I4__BYREF_I4__BYREF_I4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::SetWindowPos___STATIC__VOID__U4__I4__I4__I4__I4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::GetWindowData___STATIC__OBJECT__U4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::SetWindowData___STATIC__VOID__U4__OBJECT,
    Library_CanFly_CoreLibrary_CanFly_Syscall::GetParent___STATIC__U4__U4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::GetWindowById___STATIC__U4__U4__U2,
    Library_CanFly_CoreLibrary_CanFly_Syscall::GetFirstChild___STATIC__U4__U4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::GetNextSibling___STATIC__U4__U4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::GetPreviousSibling___STATIC__U4__U4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::InsertBefore___STATIC__VOID__U4__U4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::InsertAfter___STATIC__VOID__U4__U4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::GetZOrder___STATIC__U1__U4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::SetZOrder___STATIC__VOID__U4__U1,
    Library_CanFly_CoreLibrary_CanFly_Syscall::CanvasClose___STATIC__VOID__U4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::CreateRectCanvas___STATIC__U4__I4__I4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::CreatePngCanvas___STATIC__U4__U4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::LoadPng___STATIC__VOID__U4__U4__I4__I4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::GetCanvasExtents___STATIC__VOID__U4__BYREF_U2__BYREF_I4__BYREF_I4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::GetOrientation___STATIC__U2__U4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::SetOrientation___STATIC__VOID__U4__U2,
    Library_CanFly_CoreLibrary_CanFly_Syscall::CreatePen___STATIC__U4__U4__U2__U2,
    Library_CanFly_CoreLibrary_CanFly_Syscall::GetPenColor___STATIC__U4__U4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::GetPenWidth___STATIC__U2__U4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::GetPenStyle___STATIC__U2__U4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::DisposePen___STATIC__VOID__U4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::Polyline___STATIC__VOID__U4__I4__I4__I4__I4__U4__U4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::Ellipse___STATIC__VOID__U4__I4__I4__I4__I4__U4__U4__I4__I4__I4__I4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::Polygon___STATIC__VOID__U4__I4__I4__I4__I4__U4__U4__U4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::Rectangle___STATIC__VOID__U4__I4__I4__I4__I4__U4__U4__I4__I4__I4__I4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::RoundRect___STATIC__VOID__U4__I4__I4__I4__I4__U4__U4__I4__I4__I4__I4__I4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::BitBlt___STATIC__VOID__U4__I4__I4__I4__I4__I4__I4__I4__I4__U4__I4__I4__I4__I4__I4__I4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::GetPixel___STATIC__U4__U4__I4__I4__I4__I4__I4__I4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::SetPixel___STATIC__U4__U4__I4__I4__I4__I4__I4__I4__U4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::Arc___STATIC__VOID__U4__I4__I4__I4__I4__U4__I4__I4__I4__I4__I4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::Pie___STATIC__VOID__U4__I4__I4__I4__I4__U4__U4__I4__I4__I4__I4__I4__I4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::OpenFont___STATIC__U4__STRING__U2,
    Library_CanFly_CoreLibrary_CanFly_Syscall::DrawText___STATIC__VOID__U4__I4__I4__I4__I4__U4__U4__U4__STRING__I4__I4__I4__I4__I4__I4__U2,
    Library_CanFly_CoreLibrary_CanFly_Syscall::TextExtent___STATIC__VOID__U4__U4__STRING__BYREF_I4__BYREF_I4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::InvalidateRect___STATIC__VOID__U4__I4__I4__I4__I4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::IsValid___STATIC__BOOLEAN__U4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::BeginPaint___STATIC__VOID__U4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::EndPaint___STATIC__VOID__U4,
    Library_CanFly_CoreLibrary_CanFly_Syscall::GetMessage___STATIC__BOOLEAN__U4__BYREF_U4__BYREF_U2__BYREF_U1__BYREF_U1__BYREF_U1__BYREF_U1__BYREF_U1__BYREF_U1__BYREF_U1__BYREF_U1,
    Library_CanFly_CoreLibrary_CanFly_Syscall::DispatchMessage___STATIC__VOID__U4__U2__U2__U1__U1__U1__U1__U1__U1__U1__U1,
    Library_CanFly_CoreLibrary_CanFly_Syscall::PostMessage___STATIC__VOID__U4__U4__U2__U2__U1__U1__U1__U1__U1__U1__U1__U1,
    Library_CanFly_CoreLibrary_CanFly_Syscall::Send___STATIC__VOID__U2__U2__U1__U1__U1__U1__U1__U1__U1__U1,
    Library_CanFly_CoreLibrary_CanFly_Syscall::SendRaw___STATIC__VOID__U2__U2__U1__U1__U1__U1__U1__U1__U1__U1,
    Library_CanFly_CoreLibrary_CanFly_Syscall::SendReply___STATIC__VOID__U2__U2__U1__U1__U1__U1__U1__U1__U1__U1,
    Library_CanFly_CoreLibrary_CanFly_Syscall::GetFloat___STATIC__R4__U1__U1__U1__U1,
    Library_CanFly_CoreLibrary_CanFly_Syscall::GetInt32___STATIC__I4__U1__U1__U1__U1,
    Library_CanFly_CoreLibrary_CanFly_Syscall::GetUInt32___STATIC__U4__U1__U1__U1__U1,
    Library_CanFly_CoreLibrary_CanFly_Syscall::GetInt16___STATIC__I2__U1__U1,
    Library_CanFly_CoreLibrary_CanFly_Syscall::GetUInt16___STATIC__U2__U1__U1,
    Library_CanFly_CoreLibrary_CanFly_Syscall::PackFloat___STATIC__VOID__R4__BYREF_U1__BYREF_U1__BYREF_U1__BYREF_U1,
    Library_CanFly_CoreLibrary_CanFly_Syscall::PackInt32___STATIC__VOID__I4__BYREF_U1__BYREF_U1__BYREF_U1__BYREF_U1,
    Library_CanFly_CoreLibrary_CanFly_Syscall::PackUInt32___STATIC__VOID__U4__BYREF_U1__BYREF_U1__BYREF_U1__BYREF_U1,
    Library_CanFly_CoreLibrary_CanFly_Syscall::PackInt16___STATIC__VOID__I2__BYREF_U1__BYREF_U1,
    Library_CanFly_CoreLibrary_CanFly_Syscall::PackUInt16___STATIC__VOID__U2__BYREF_U1__BYREF_U1,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_canflylib =
{
    "CanFly.CoreLibrary",
    0x30CDF74E,
    method_lookup,
    { 1, 0, 0, 0 }
};

// clang-format on
